### ISSUE TITLE
springboot启动报错

### ISSUE THREAD

**Issue by gx96** [jeecgboot/JimuReport#1022]
##### 错误日志&截图：

Error creating bean with name 'designReportController': Unsatisfied dependency expressed through field 'reportDbService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jmReportDbServiceImpl': Unsatisfied dependency expressed through field 'jmReportParamService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jmReportDbParamServiceImpl': Injection of autowired dependencies failed; nested exception is java.lang.LinkageError: loader constraint violation in interface itable initialization: when resolving method "com.sun.proxy.$Proxy139.qurestechSql(Lorg/jeecg/modules/jmreport/desreport/entity/JmReportDb;Lcom/alibaba/fastjson/JSONObject;)Ljava/util/List;" the class loader (instance of org/springframework/boot/devtools/restart/classloader/RestartClassLoader) of the current class, com/sun/proxy/$Proxy139, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for interface org/jeecg/modules/jmreport/desreport/service/IJmReportDbService have different Class objects for the type com/alibaba/fastjson/JSONObject used in the signature

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
1.5.0 fastjson版本为1.2.83 看看是不是冲突的原因

**Comment by gx96** [comment]
> 1.5.0 fastjson版本为1.2.83 看看是不是冲突的原因
换了1.2.83还是一样的问题，我看源码，1.5.0是IJmReportDbService下的qurestechSql(JmReportDb var1, JSONObject var2)接口，比1.5.0-beta多了第二个 JSONObject var2参数。

**Comment by lvdandan16** [comment]
应该不是这个问题，我更新下来，没问题

**Comment by Fxiao1** [comment]
我也遇到了这个问题，集成不进来，集成之后启动的时候就报错

```java
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'designReportController': Unsatisfied dependency expressed through field 'reportDbService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jmReportDbServiceImpl': Unsatisfied dependency expressed through field 'jmReportParamService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jmReportDbParamServiceImpl': Injection of autowired dependencies failed; nested exception is java.lang.LinkageError: loader constraint violation in interface itable initialization: when resolving method "com.sun.proxy.$Proxy135.qurestechSql(Lorg/jeecg/modules/jmreport/desreport/entity/JmReportDb;Lcom/alibaba/fastjson/JSONObject;)Ljava/util/List;" the class loader (instance of org/springframework/boot/devtools/restart/classloader/RestartClassLoader) of the current class, com/sun/proxy/$Proxy135, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for interface org/jeecg/modules/jmreport/desreport/service/IJmReportDbService have different Class objects for the type com/alibaba/fastjson/JSONObject used in the signature
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:453)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1359)
	at com.ruoyi.RuoYiApplication.main(RuoYiApplication.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
```

若依版本是`3.8.2`，积木报表的版本是`1.5.0`，按照的就是官网的[这个方法](http://report.jeecg.com/2302148)操作的

**Comment by gx96** [comment]
> 我也遇到了这个问题，集成不进来，集成之后启动的时候就报错了
> 
> ```java
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'designReportController': Unsatisfied dependency expressed through field 'reportDbService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jmReportDbServiceImpl': Unsatisfied dependency expressed through field 'jmReportParamService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jmReportDbParamServiceImpl': Injection of autowired dependencies failed; nested exception is java.lang.LinkageError: loader constraint violation in interface itable initialization: when resolving method "com.sun.proxy.$Proxy135.qurestechSql(Lorg/jeecg/modules/jmreport/desreport/entity/JmReportDb;Lcom/alibaba/fastjson/JSONObject;)Ljava/util/List;" the class loader (instance of org/springframework/boot/devtools/restart/classloader/RestartClassLoader) of the current class, com/sun/proxy/$Proxy135, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for interface org/jeecg/modules/jmreport/desreport/service/IJmReportDbService have different Class objects for the type com/alibaba/fastjson/JSONObject used in the signature
> 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659)
> 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
> 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
> 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
> 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780)
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:453)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:343)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1370)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1359)
> 	at com.ruoyi.RuoYiApplication.main(RuoYiApplication.java:18)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
> ```
> 
> 如果依版本是`3.8.2`，积木报告的版本是`1.5.0`，按照的就是官网的[这个方法](http://report.jeecg.com/2302148)操作的

更新一下积木1.5.1，不报错了
