### ISSUE TITLE
1.5.0版本样例项目，打war包发布到tomcat启动后访问不了，jdk1.8，tomcat8.5.24

### ISSUE THREAD

**Issue by XanderChnn** [jeecgboot/JimuReport#1064]
##### 版本号：
1.5.0

##### 问题描述：
本地启动没有问题，可正常访问，将项目打成war包发布，启动报个错，页面也访问不了

##### 错误日志&截图：
 org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load []. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load []. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1311)
        at org.apache.catalina.loader.WebappClassLoaderBase.getResource(WebappClassLoaderBase.java:986)
        at com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.checkThreadContextClassLoader(AbandonedConnectionCleanupThread.java:123)
        at com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:90)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

##### 重现步骤：
jdk版本1.8
1.打1.5.0版本打war
2.发布到tomcat8
3.启动报错，页面访问不了

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
打war包可以使用tomcat9   或直接使用jar包方式运行
