### ISSUE TITLE
字典缓存刷新,新增均报错(紧急)

### ISSUE THREAD

**Issue by Acechengui** [jeecgboot/JimuReport#1188]
##### 版本号：
1.5.2

##### 问题描述：
字典无法刷新缓存,无法新增,原做好的报表也无法预览访问

##### 错误日志&截图：
ERROR c.j.c.s.h.GlobalExceptionHandler - [handleRuntimeException,109] - 请求地址'/jmreport/getQueryInfo',发生未知异常.
java.lang.IllegalArgumentException: Cannot find cache named 'jmreport:cache:dict' for Builder[public java.util.List org.jeecg.modules.jmreport.desreport.service.a.c.queryDictItemsByCode(java.lang.String)] caches=[jmreport:cache:dict] | key='#code' | keyGenerator='' | cacheManager='' | cacheResolver='' | condition='' | unless='#result == null || #result.size()==0' | sync='false'
	at org.springframework.cache.interceptor.AbstractCacheResolver.resolveCaches(AbstractCacheResolver.java:92)
	at org.springframework.cache.interceptor.CacheAspectSupport.getCaches(CacheAspectSupport.java:252)
	at org.springframework.cache.interceptor.CacheAspectSupport$CacheOperationContext.<init>(CacheAspectSupport.java:724)
	at org.springframework.cache.interceptor.CacheAspectSupport.getOperationContext(CacheAspectSupport.java:265)
	at org.springframework.cache.interceptor.CacheAspectSupport$CacheOperationContexts.<init>(CacheAspectSupport.java:615)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.jeecg.modules.jmreport.desreport.service.a.c$$EnhancerBySpringCGLIB$$9dd07c7b.queryDictItemsByCode(<generated>)
	at org.jeecg.modules.jmreport.desreport.service.a.e.queryDictListByCode(JimuReportServiceImpl.java:3490)
	at org.jeecg.modules.jmreport.desreport.service.a.e.getReportQueryInfo(JimuReportServiceImpl.java:3362)
	at org.jeecg.modules.jmreport.desreport.service.a.e$$FastClassBySpringCGLIB$$4daca651.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

##### 重现步骤：
本地启动,连接的远程redis,与线上的使用的同一redis,检查redis访问正常,线上因未更新积木报表版本,暂无此问题,

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by Acechengui** [comment]
已解决,原因是speingboot版本不兼容问题,2.6.x正常,升级至2.7.x数据字典报错,只好回退springboot版本

**Comment by gumuqing** [comment]
@Acechengui 请问下speingboot版本用2.7.x时，不降低speingboot版本后面有其它解决方法吗？
