### ISSUE TITLE
导出excel报错：NullPointerException

### ISSUE THREAD

**Issue by xkzhang76** [jeecgboot/JimuReport#1322]
##### 版本号：
1.5.2

##### 问题描述：
模板案例导出excel报错，自己创建的报表导出excel也报错

##### 错误日志&截图：

> 15:38:41.425 [http-nio-29204-exec-4] INFO  o.j.m.j.d.s.a.e - [getDataById,267] - ------报表【pop】，查询的sql: select * from rep_demo_dxtj
15:38:41.684 [http-nio-29204-exec-4] ERROR c.e.c.s.h.GlobalExceptionHandler - [handleRuntimeException,82] - 请求地址'/jmreport/exportAllExcelStream',发生未知异常.
java.lang.NullPointerException: null
	at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:608)
	at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:162)
	at org.jeecg.modules.jmreport.desreport.service.a.k.exportExcel(JmReportExportExcelImpl.java:118)
	at org.jeecg.modules.jmreport.desreport.service.a.k$$FastClassBySpringCGLIB$$4daca657.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at com.baomidou.dynamic.datasource.aop.DynamicDatasourceNamedInterceptor.invoke(DynamicDatasourceNamedInterceptor.java:58)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at org.jeecg.modules.jmreport.desreport.service.a.k$$EnhancerBySpringCGLIB$$2f04f72d.exportExcel(<generated>)
	at org.jeecg.modules.jmreport.desreport.a.a.b(DesignReportController.java:1163)
	at org.jeecg.modules.jmreport.desreport.a.a$$FastClassBySpringCGLIB$$91776b06.invoke(<generated>)

> 15:41:37.328 [http-nio-29204-exec-8] ERROR c.e.c.s.h.GlobalExceptionHandler - [handleRuntimeException,82] - 请求地址'/jmreport/exportAllExcelStream',发生未知异常.
java.lang.NullPointerException: null
	at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:608)
	at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:246)
	at org.jeecg.modules.jmreport.desreport.service.a.k.exportExcel(JmReportExportExcelImpl.java:123)
	at org.jeecg.modules.jmreport.desreport.service.a.k$$FastClassBySpringCGLIB$$4daca657.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at com.baomidou.dynamic.datasource.aop.DynamicDatasourceNamedInterceptor.invoke(DynamicDatasourceNamedInterceptor.java:58)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at org.jeecg.modules.jmreport.desreport.service.a.k$$EnhancerBySpringCGLIB$$2f04f72d.exportExcel(<generated>)
	at org.jeecg.modules.jmreport.desreport.a.a.b(DesignReportController.java:1163)
	at org.jeecg.modules.jmreport.desreport.a.a$$FastClassBySpringCGLIB$$91776b06.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at com.baomidou.dynamic.datasource.aop.DynamicDatasourceNamedInterceptor.invoke(DynamicDatasourceNamedInterceptor.java:58)

##### 重现步骤：
集成在ruoyi-cloud服务
使用了dynamic-datasource-spring-boot-starter-3.5.0
多选查询条件报表案例模板：/jmreport/view/1338769064067076098，其他的也报错

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by xkzhang76** [comment]
导出pdf是正常的

**Comment by xkzhang76** [comment]
`if (var34.size() >= this.jmBaseConfig.excelStyleRow && var41 instanceof XSSFSheet) {
        }`
this.jmBaseConfig.excelStyleRow 修改为 this.jmBaseConfig.getExcelStyleRow() 应该可以获取到值

![image](https://user-images.githubusercontent.com/26195769/193240203-8f70be6e-39d0-4316-b7a6-8a3336c97446.png)

**Comment by lvdandan16** [comment]
报表数据是不是有的数据为空？所有的报表都有问题？

**Comment by xkzhang76** [comment]
> 报表数据是不是有的数据为空？所有的报表都有问题？

检查了下，没有空数据，甚至初始化的报表模板案例，也是报错，
跟踪了下代码，发现大概是取 this.jmBaseConfig.excelStyleRow为null

**Comment by lvdandan16** [comment]
我这里未复现你说的这个问题，直接新建个报表，写个简单的字符串直接导出，如果还有问题，那可能是与你自己的项目有冲突；或者可以直接用demo试一下1.5.2看有没有问题

**Comment by xkzhang76** [comment]
> 我这里未复现你说的这个问题，直接新建个报表，写个简单的字符串直接导出，如果还有问题，那可能是与你自己的项目有冲突；或者可以直接用demo试一下1.5.2看有没有问题

应该是集成项目后，遇到了this.jmBaseConfig.excelStyleRow为null的情况

**Comment by xkzhang76** [comment]
源码：
> @Configuration("jmReportBaseConfig")
@ConfigurationProperties(prefix = "jeecg.jmreport")
 public class JmReportBaseConfig
 {

复制到项目一份：
>  @Configuration("jmReportBaseConfig1")
 @ConfigurationProperties(prefix = "jeecg.jmreport")
public class JmReportBaseConfig1
 {

配置文件：
> jeecg :
   jmreport:
    #excel样式超过多少行显示默认样式（只在fast模式下有效）
    excel-style-row: 10

测试读取：

> @RestController
@RequestMapping("/code")
public class CodeController {
    @Autowired
    private JmReportBaseConfig1 jmBaseConfig1;
    @Autowired
    private org.jeecg.modules.jmreport.config.JmReportBaseConfig jmBaseConfig;
  
    @GetMapping("/info")
    public void info() {
        System.out.println(jmBaseConfig1.excelStyleRow);  //10
        System.out.println(jmBaseConfig1.getExcelStyleRow()); //10
        System.out.println("====================================");
        System.out.println(jmBaseConfig.excelStyleRow); //null
        System.out.println(jmBaseConfig.getExcelStyleRow()); //10
    }
