### ISSUE TITLE
新版本的积木报表在tomcat8.5上会报过滤器异常

### ISSUE THREAD

**Issue by MXKLJC** [jeecgboot/JimuReport#1450]
##### 版本号：
1.5.4

##### 问题描述：
tomcat8.5上部署报过滤器异常，目测是继承filter类时没有重写init方法引起的兼容性问题

##### 错误日志&截图：
21-Nov-2022 11:19:59.036 严重 [localhost-startStop-1] org.apache.catalina.core.StandardContext.filterStart 启动过滤器异常[jmFilter]
	java.lang.AbstractMethodError
		at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:281)
		at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:109)
		at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4609)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5259)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:727)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1016)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1903)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:750)

##### 重现步骤：
项目打包部署在tomcat8.5上

**Comment by lvdandan16** [comment]
建议使用tomcat9
