### ISSUE TITLE
积木报表导出图表时报Cannot invoke "java.util.List.size()"

### ISSUE THREAD

**Issue by gmm4210** [jeecgboot/JimuReport#1582]
##### 版本号：
jimureport-spring-boot-starter-1.5.2.jar

##### 问题描述：
单纯的导出表格不报错，导出柱状图或是其他图时报错

##### 错误日志&截图：
08:26:54.390 ERROR [http-nio-8080-exec-2] [c.c.w.m.c.ExceptionController]:1643 - Cannot invoke "java.util.List.size()" because "<parameter2>" is null
08:26:54.390 ERROR [http-nio-8080-exec-2] [c.c.w.m.c.ExceptionController]:1644 - java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "<parameter2>" is null
	at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:509)
	at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:246)
	at org.jeecg.modules.jmreport.desreport.service.a.k.exportExcel(JmReportExportExcelImpl.java:123)
	at org.jeecg.modules.jmreport.desreport.a.a.a(DesignReportController.java:1110)

##### 重现步骤：
必现
![1](https://user-images.githubusercontent.com/19221673/211434934-59428e0f-1017-404e-a530-0b3fb0f3b6a6.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
测试未复现，请升级到最版本试试
