### ISSUE TITLE
多数据集与分栏功能共同使用时报NTP

### ISSUE THREAD

**Issue by phsy** [jeecgboot/JimuReport#1587]
##### 问题描述：
报表有固定信息和循环块，固定信息和循环块来自不同的数据集，其中固定信息是单条数据，循环块是多条数据，可以正常渲染，但是导出时报空指针错误

##### 错误日志&截图：
模板ID：772697586829447168
![image](https://user-images.githubusercontent.com/10345070/211776566-ea66a2db-af6b-460f-88a4-9ac806e5b053.png)
导出的文件里只有错误信息
![image](https://user-images.githubusercontent.com/10345070/211777228-8e90888b-38d7-42ef-b795-bc9f88604f79.png)

错误堆栈：
ERROR] 2023-01-11T17:41:51,250 [http-nio-30004-exec-3] GlobalControllerAdvice - null
java.lang.NullPointerException
	at org.jeecg.modules.jmreport.desreport.render.a.a.a(LoopBlockRenderStrategy.java:263)
	at org.jeecg.modules.jmreport.desreport.render.a.a.a(LoopBlockRenderStrategy.java:330)
	at org.jeecg.modules.jmreport.desreport.render.a.a.b(LoopBlockRenderStrategy.java:201)
	at org.jeecg.modules.jmreport.desreport.render.a.a.b.a(BaseBaseRenderStrategy.java:417)
	at org.jeecg.modules.jmreport.desreport.render.a.a.b.c(BaseBaseRenderStrategy.java:54)
	at org.jeecg.modules.jmreport.desreport.service.a.e.a(JimuReportServiceImpl.java:3850)
	at org.jeecg.modules.jmreport.desreport.service.a.e.show(JimuReportServiceImpl.java:3749)
	at org.jeecg.modules.jmreport.desreport.service.a.e$$FastClassBySpringCGLIB$$4daca651.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
	at org.jeecg.modules.jmreport.desreport.service.a.e$$EnhancerBySpringCGLIB$$7cc85a64.show(<generated>)
	at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:287)
	at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:232)
	at org.jeecg.modules.jmreport.desreport.service.a.k.exportExcel(JmReportExportExcelImpl.java:130)
	at org.jeecg.modules.jmreport.desreport.a.a.b(DesignReportController.java:1190)
	at sun.reflect.GeneratedMethodAccessor380.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
            ......

##### 重现步骤：
设置两个数据集，一个数据集只有一条数据（作为固定信息），一个数据集有多条数据（循环块），先设置固定信息，下方设置循环块并做分栏，点击预览，点击导出，打开导出文件。

对模板进行多次调整后，发现以下规律：
固定信息在循环块之前：报错
固定信息在循环块之后：正常
只使用循环块：正常

**Comment by lvdandan16** [comment]
收录 ws

**Comment by 1298191366** [comment]
现在没有问题了，已经修复过了，升级到1.6.1版本试一下
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.6.1</version>
</dependency>
```
