### ISSUE TITLE
sql执行正常渲染报错

### ISSUE THREAD

**Issue by xiayeCode** [jeecgboot/JimuReport#1621]
##### 版本号：

1.5.4
##### 问题描述：
![image](https://user-images.githubusercontent.com/17448036/216871647-784898de-4a17-4e8b-a47b-0ef2e545e5e4.png)
sql执行正常渲染报错

java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.jeecg.modules.jmreport.common.b.g.a(OkConvertUtils.java:155)
	at org.jeecg.modules.jmreport.desreport.render.utils.RenderUtil.j(RenderUtil.java:906)
	at org.jeecg.modules.jmreport.desreport.render.a.c.a(TableGroupRenderStrategy.java:63)
	at org.jeecg.modules.jmreport.desreport.render.a.a.b.a(BaseBaseRenderStrategy.java:352)
	at org.jeecg.modules.jmreport.desreport.render.a.a.b.b(BaseBaseRenderStrategy.java:259)
	at org.jeecg.modules.jmreport.desreport.render.a.a.b.c(BaseBaseRenderStrategy.java:56)
	at org.jeecg.modules.jmreport.desreport.service.a.e.a(JimuReportServiceImpl.java:3848)
	at org.jeecg.modules.jmreport.desreport.service.a.e.show(JimuReportServiceImpl.java:3747)
	at org.jeecg.modules.jmreport.desreport.service.a.e$$FastClassBySpringCGLIB$$4daca651.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.jeecg.modules.jmreport.desreport.service.a.e$$EnhancerBySpringCGLIB$$7a836476.show(<generated>)
	at org.jeecg.modules.jmreport.desreport.a.a.a(DesignReportController.java:382)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/17448036/216871649-d3449e58-82d7-40c5-8ca6-28431accc0cf.png)

sql执行正常渲染报错

##### 重现步骤：
sql执行正常渲染报错

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by liquanyou** [comment]
这种情况最好先指定一下字段的属性

**Comment by zhangdaiscott** [comment]
你没输入sql吗
