### ISSUE TITLE
报表的数据集无法保存，Unrecognized field "tableIndex" 

### ISSUE THREAD

**Issue by ricky0149** [jeecgboot/JimuReport#1636]
##### 版本号：

1.5.6
1.5.2
尝试了2个版本，都报错
##### 问题描述：
新建报表，创建数据集无法保存，点保存无反应，后台产生错误信息。

现在怀疑自己的springboot (2.1.17 )项目在集成积木时，有类库冲突，但pom 显示没有冲突，没有找到线索。

##### 错误日志&截图：

org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Unrecognized field "tableIndex" (class org.jeecg.modules.jmreport.desreport.entity.JmReportDbField), not marked as ignorable; nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "tableIndex" (class org.jeecg.modules.jmreport.desreport.entity.JmReportDbField), not marked as ignorable (17 known properties: "updateBy", "widgetWidth", "dictCode", "fieldName", "fieldText", "searchValue", "searchMode", "createBy", "jimuReportDbId", "updateTime", "orderNum", "id", "widgetType", "searchFormat", "createTime", "searchFlag", "extJson"])
 at [Source: (PushbackInputStream); line: 1, column: 320] (through reference chain: org.jeecg.modules.jmreport.desreport.entity.JmReportDb["fieldList"]->java.util.ArrayList[0]->org.jeecg.modules.jmreport.desreport.entity.JmReportDbField["tableIndex"])
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:283)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:241)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:205)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:158)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:131)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:127)
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:167)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "tableIndex" (class org.jeecg.modules.jmreport.desreport.entity.JmReportDbField), not marked as ignorable (17 known properties: "updateBy", "widgetWidth", "dictCode", "fieldName", "fieldText", "searchValue", "searchMode", "createBy", "jimuReportDbId", "updateTime", "orderNum", "id", "widgetType", "searchFormat", "createTime", "searchFlag", "extJson"])
 at [Source: (PushbackInputStream); line: 1, column: 320] (through reference chain: org.jeecg.modules.jmreport.desreport.entity.JmReportDb["fieldList"]->java.util.ArrayList[0]->org.jeecg.modules.jmreport.desreport.entity.JmReportDbField["tableIndex"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4014)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3085)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:272)
	... 91 common frames omitted
13:40:47.721 [http-nio-9088-exec-6] WARN  o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver - [logException,199] - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Unrecognized field "tableIndex" (class org.jeecg.modules.jmreport.desreport.entity.JmReportDbField), not marked as ignorable; nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "tableIndex" (class org.jeecg.modules.jmreport.desreport.entity.JmReportDbField), not marked as ignorable (17 known properties: "updateBy", "widgetWidth", "dictCode", "fieldName", "fieldText", "searchValue", "searchMode", "createBy", "jimuReportDbId", "updateTime", "orderNum", "id", "widgetType", "searchFormat", "createTime", "searchFlag", "extJson"])
 at [Source: (PushbackInputStream); line: 1, column: 320] (through reference chain: org.jeecg.modules.jmreport.desreport.entity.JmReportDb["fieldList"]->java.util.ArrayList[0]->org.jeecg.modules.jmreport.desreport.entity.JmReportDbField["tableIndex"])]
13:41:47.910 [schedule-pool-2] INFO  c.c.n.f.s.w.s.OnlineWebSessionManager - [validateSessions,100] - invalidation sessions...

##### 重现步骤：
新建报表，创建数据集合，可以预览数据。 保存没反应。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by ricky0149** [comment]
<img width="451" alt="image" src="https://user-images.githubusercontent.com/125142644/218267558-09717f79-d39b-4122-87a8-2ade17fc2aaf.png">

Maven: antlr:antlr:2.7.7
Maven: ch.qos.logback:logback-classic:1.2.3
Maven: ch.qos.logback:logback-core:1.2.3
Maven: cn.afterturn:easypoi-annotation:4.4.0
Maven: cn.afterturn:easypoi-base:4.4.0
Maven: cn.afterturn:easypoi-web:4.4.0
Maven: cn.hutool:hutool-all:5.5.2
Maven: com.alibaba:druid:1.2.8
Maven: com.alibaba:druid-spring-boot-starter:1.2.8
Maven: com.alibaba:fastjson:1.2.83
Maven: com.aliyun.oss:aliyun-sdk-oss:3.11.2
Maven: com.aliyun:aliyun-java-sdk-core:4.5.10
Maven: com.aliyun:aliyun-java-sdk-kms:2.11.0
Maven: com.aliyun:aliyun-java-sdk-ram:3.1.0
Maven: com.carrotsearch.thirdparty:simple-xml-safe:2.7.1
Maven: com.carrotsearch:java-sizeof:0.0.5
Maven: com.fasterxml.jackson.core:jackson-annotations:2.13.2
Maven: com.fasterxml.jackson.core:jackson-core:2.13.2
Maven: com.fasterxml.jackson.core:jackson-databind:2.13.2
Maven: com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.2
Maven: com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.2
Maven: com.fasterxml.jackson.module:jackson-module-parameter-names:2.13.2
Maven: com.fasterxml:classmate:1.4.0
Maven: com.github.jsqlparser:jsqlparser:4.3
Maven: com.github.librepdf:openpdf:1.3.27
Maven: com.github.oshi:oshi-core:5.2.5
Maven: com.github.pagehelper:pagehelper:5.2.0
Maven: com.github.pagehelper:pagehelper-spring-boot-autoconfigure:1.3.0
Maven: com.github.pagehelper:pagehelper-spring-boot-starter:1.3.0
Maven: com.github.penggle:kaptcha:2.3.2
Maven: com.github.theborakompanioni:thymeleaf-extras-shiro:2.0.0
Maven: com.github.virtuald:curvesapi:1.06
Maven: com.google.code.findbugs:jsr305:3.0.2
Maven: com.google.code.gson:gson:2.8.5
Maven: com.google.code.gson:gson:2.8.6
Maven: com.google.errorprone:error_prone_annotations:2.5.1
Maven: com.google.guava:failureaccess:1.0.1
Maven: com.google.guava:guava:30.1.1-jre
Maven: com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
Maven: com.google.j2objc:j2objc-annotations:1.3
Maven: com.google.protobuf:protobuf-java:3.4.0
Maven: com.google.zxing:core:3.3.1
Maven: com.googlecode.aviator:aviator:5.2.6
Maven: com.googlecode.json-simple:json-simple:1.1
Maven: com.googlecode.protobuf-java-format:protobuf-java-format:1.4
Maven: com.inversoft:prime-jwt:1.3.1
Maven: com.jayway.jsonpath:json-path:2.4.0
Maven: com.jhlabs:filters:2.0.235-1
Maven: com.mchange:mchange-commons-java:0.2.15
Maven: com.squareup.okhttp3:okhttp:4.8.1
Maven: com.squareup.okio:okio:2.7.0
Maven: com.sun.istack:istack-commons-runtime:3.0.7
Maven: com.sun.mail:javax.mail:1.6.2
Maven: com.sun.xml.fastinfoset:FastInfoset:1.2.15
Maven: com.thoughtworks.paranamer:paranamer:2.8
Maven: com.vaadin.external.google:android-json:0.0.20131108.vaadin1
Maven: com.zaxxer:HikariCP:3.2.0
Maven: com.zaxxer:SparseBitSet:1.2
Maven: commons-beanutils:commons-beanutils:1.9.4
Maven: commons-codec:commons-codec:1.11
Maven: commons-collections:commons-collections:3.2.2
Maven: commons-dbcp:commons-dbcp:1.4
Maven: commons-fileupload:commons-fileupload:1.3.3
Maven: commons-io:commons-io:2.5
Maven: commons-lang:commons-lang:2.4
Maven: commons-logging:commons-logging:1.2
Maven: commons-pool:commons-pool:1.6
Maven: de.odysseus.juel:juel-api:2.2.7
Maven: de.odysseus.juel:juel-impl:2.2.7
Maven: de.odysseus.juel:juel-spi:2.2.7
Maven: eu.bitwalker:UserAgentUtils:1.20
Maven: io.minio:minio:8.0.3
Maven: io.netty:netty-all:4.1.6.Final
Maven: io.opentracing:opentracing-api:0.33.0
Maven: io.opentracing:opentracing-noop:0.33.0
Maven: io.opentracing:opentracing-util:0.33.0
Maven: io.springfox:springfox-core:2.9.2
Maven: io.springfox:springfox-schema:2.9.2
Maven: io.springfox:springfox-spi:2.9.2
Maven: io.springfox:springfox-spring-web:2.9.2
Maven: io.springfox:springfox-swagger2:2.9.2
Maven: io.springfox:springfox-swagger-common:2.9.2
Maven: io.springfox:springfox-swagger-ui:2.9.2
Maven: io.swagger:swagger-annotations:1.5.10
Maven: io.swagger:swagger-annotations:1.5.21
Maven: io.swagger:swagger-models:1.5.10
Maven: io.swagger:swagger-models:1.5.21
Maven: javax.activation:activation:1.1
Maven: javax.activation:javax.activation-api:1.2.0
Maven: javax.annotation:javax.annotation-api:1.3.2
Maven: javax.annotation:jsr250-api:1.0
Maven: javax.mail:mail:1.4.7
Maven: javax.persistence:javax.persistence-api:2.2
Maven: javax.servlet:javax.servlet-api:4.0.1
Maven: javax.transaction:javax.transaction-api:1.3
Maven: javax.validation:validation-api:2.0.1.Final
Maven: javax.xml.bind:jaxb-api:2.3.1
Maven: joda-time:joda-time:2.10.6
Maven: junit:junit:4.12
Maven: ma.glasnost.orika:orika-core:1.5.4
Maven: math.geom2d:javaGeom:0.11.1
Maven: mysql:mysql-connector-java:8.0.21
Maven: net.bytebuddy:byte-buddy:1.9.16
Maven: net.bytebuddy:byte-buddy-agent:1.9.16
Maven: net.java.dev.jna:jna:5.5.0
Maven: net.java.dev.jna:jna-platform:5.5.0
Maven: net.minidev:accessors-smart:1.2
Maven: net.minidev:json-smart:2.3
Maven: net.rakugakibox.spring.boot:orika-spring-boot-starter:1.9.0
Maven: net.sf.ehcache:ehcache-core:2.6.11
Maven: ognl:ognl:3.2.6
Maven: ognl:ognl:3.2.21
Maven: org.activiti:activiti-bpmn-converter:6.0.0
Maven: org.activiti:activiti-bpmn-model:6.0.0
Maven: org.activiti:activiti-common-rest:6.0.0
Maven: org.activiti:activiti-dmn-api:6.0.0
Maven: org.activiti:activiti-dmn-model:6.0.0
Maven: org.activiti:activiti-engine:6.0.0
Maven: org.activiti:activiti-form-api:6.0.0
Maven: org.activiti:activiti-form-model:6.0.0
Maven: org.activiti:activiti-image-generator:6.0.0
Maven: org.activiti:activiti-json-converter:6.0.0
Maven: org.activiti:activiti-process-validation:6.0.0
Maven: org.activiti:activiti-rest:6.0.0
Maven: org.activiti:activiti-spring:6.0.0
Maven: org.activiti:activiti-spring-boot-starter-basic:6.0.0
Maven: org.activiti:activiti-spring-boot-starter-rest-api:6.0.0
Maven: org.apache.avalon.framework:avalon-framework-api:4.3.1
Maven: org.apache.avalon.framework:avalon-framework-impl:4.3.1
Maven: org.apache.commons:commons-collections4:4.4
Maven: org.apache.commons:commons-compress:1.19
Maven: org.apache.commons:commons-email:1.4
Maven: org.apache.commons:commons-lang3:3.8.1
Maven: org.apache.commons:commons-math3:3.6.1
Maven: org.apache.commons:commons-pool2:2.6.2
Maven: org.apache.httpcomponents:httpclient:4.5.12
Maven: org.apache.httpcomponents:httpcore:4.4.13
Maven: org.apache.logging.log4j:log4j-api:2.11.2
Maven: org.apache.logging.log4j:log4j-to-slf4j:2.11.2
Maven: org.apache.poi:ooxml-schemas:1.4
Maven: org.apache.poi:poi:4.1.2
Maven: org.apache.poi:poi-ooxml:4.1.2
Maven: org.apache.poi:poi-ooxml-schemas:4.1.2
Maven: org.apache.poi:poi-scratchpad:4.1.2
Maven: org.apache.shiro:shiro-cache:1.9.0
Maven: org.apache.shiro:shiro-config-core:1.9.0
Maven: org.apache.shiro:shiro-config-ogdl:1.9.0
Maven: org.apache.shiro:shiro-core:1.9.0
Maven: org.apache.shiro:shiro-crypto-cipher:1.9.0
Maven: org.apache.shiro:shiro-crypto-core:1.9.0
Maven: org.apache.shiro:shiro-crypto-hash:1.9.0
Maven: org.apache.shiro:shiro-ehcache:1.9.0
Maven: org.apache.shiro:shiro-event:1.9.0
Maven: org.apache.shiro:shiro-lang:1.9.0
Maven: org.apache.shiro:shiro-spring:1.9.0
Maven: org.apache.shiro:shiro-web:1.9.0
Maven: org.apache.tomcat.embed:tomcat-embed-core:9.0.38
Maven: org.apache.tomcat.embed:tomcat-embed-el:9.0.38
Maven: org.apache.tomcat.embed:tomcat-embed-websocket:9.0.38
Maven: org.apache.velocity:velocity:1.7
Maven: org.apache.xmlbeans:xmlbeans:3.1.0
Maven: org.apache.xmlgraphics:batik-anim:1.7
Maven: org.apache.xmlgraphics:batik-awt-util:1.7
Maven: org.apache.xmlgraphics:batik-bridge:1.7
Maven: org.apache.xmlgraphics:batik-codec:1.7
Maven: org.apache.xmlgraphics:batik-css:1.7
Maven: org.apache.xmlgraphics:batik-dom:1.7
Maven: org.apache.xmlgraphics:batik-ext:1.7
Maven: org.apache.xmlgraphics:batik-gvt:1.7
Maven: org.apache.xmlgraphics:batik-js:1.7
Maven: org.apache.xmlgraphics:batik-parser:1.7
Maven: org.apache.xmlgraphics:batik-script:1.7
Maven: org.apache.xmlgraphics:batik-svg-dom:1.7
Maven: org.apache.xmlgraphics:batik-svggen:1.7
Maven: org.apache.xmlgraphics:batik-transcoder:1.7
Maven: org.apache.xmlgraphics:batik-util:1.7
Maven: org.apache.xmlgraphics:batik-xml:1.7
Maven: org.apache.xmlgraphics:fop:0.94
Maven: org.apache.xmlgraphics:xmlgraphics-commons:1.2
Maven: org.aspectj:aspectjrt:1.9.6
Maven: org.aspectj:aspectjweaver:1.9.6
Maven: org.assertj:assertj-core:3.11.1
Maven: org.attoparser:attoparser:2.0.5.RELEASE
Maven: org.checkerframework:checker-qual:3.8.0
Maven: org.codehaus.janino:commons-compiler:3.0.16
Maven: org.codehaus.janino:janino:3.0.16
Maven: org.codehaus.jettison:jettison:1.1
Maven: org.directwebremoting:dwr:3.0.2-RELEASE
Maven: org.dom4j:dom4j:2.1.3
Maven: org.freemarker:freemarker:2.3.30
Maven: org.glassfish.jaxb:jaxb-runtime:2.3.1
Maven: org.glassfish.jaxb:txw2:2.3.1
Maven: org.hamcrest:hamcrest-core:1.3
Maven: org.hamcrest:hamcrest-library:1.3
Maven: org.hibernate.common:hibernate-commons-annotations:5.0.4.Final
Maven: org.hibernate.validator:hibernate-validator:6.0.20.Final
Maven: org.hibernate:hibernate-core:5.3.18.Final
Maven: org.ini4j:ini4j:0.5.4
Maven: org.jacoco:org.jacoco.agent:runtime:0.8.5
Maven: org.javassist:javassist:3.29.0-GA
Maven: org.jboss.logging:jboss-logging:3.3.3.Final
Maven: org.jboss:jandex:2.0.5.Final
Maven: org.jdom:jdom2:2.0.6
Maven: org.jeecgframework.jimureport:jimureport-font:1.1.0
Maven: org.jeecgframework.jimureport:jimureport-spring-boot-starter:1.5.2
Maven: org.jeecgframework:autopoi:1.4.0
Maven: org.jeecgframework:autopoi-web:1.4.0
Maven: org.jeecgframework:minidao-pe:1.9.0
Maven: org.jeecgframework:minidao-spring-boot-starter:1.9.0
Maven: org.jetbrains.kotlin:kotlin-stdlib:1.2.71
Maven: org.jetbrains.kotlin:kotlin-stdlib-common:1.7.10
Maven: org.jetbrains:annotations:13.0
Maven: org.json:json:20210307
Maven: org.jsoup:jsoup:1.7.3
Maven: org.jvnet.staxex:stax-ex:1.8
Maven: org.mapstruct:mapstruct:1.2.0.Final
Maven: org.mockito:mockito-core:2.23.4
Maven: org.modelmapper:modelmapper:2.4.2
Maven: org.mongodb:bson:3.8.2
Maven: org.mongodb:mongodb-driver-core:3.8.2
Maven: org.mongodb:mongodb-driver-sync:4.4.2
Maven: org.mybatis.spring.boot:mybatis-spring-boot-autoconfigure:2.1.3
Maven: org.mybatis.spring.boot:mybatis-spring-boot-starter:2.1.3
Maven: org.mybatis:mybatis:3.5.5
Maven: org.mybatis:mybatis-spring:2.0.5
Maven: org.objenesis:objenesis:2.6
Maven: org.ow2.asm:asm:5.0.3
Maven: org.ow2.asm:asm:5.0.4
Maven: org.ow2.asm:asm-analysis:5.0.3
Maven: org.ow2.asm:asm-tree:5.0.3
Maven: org.ow2.asm:asm-util:5.0.3
Maven: org.owasp.encoder:encoder:1.2.2
Maven: org.parboiled:parboiled-core:1.1.7
Maven: org.parboiled:parboiled-java:1.1.7
Maven: org.pegdown:pegdown:1.6.0
Maven: org.projectlombok:lombok:1.18.12
Maven: org.quartz-scheduler:quartz:2.3.2
Maven: org.skyscreamer:jsonassert:1.5.0
Maven: org.slf4j:jcl-over-slf4j:1.7.30
Maven: org.slf4j:jul-to-slf4j:1.7.30
Maven: org.slf4j:slf4j-api:1.7.30
Maven: org.springframework.boot:spring-boot:2.1.17.RELEASE
Maven: org.springframework.boot:spring-boot-autoconfigure:2.1.17.RELEASE
Maven: org.springframework.boot:spring-boot-devtools:2.1.17.RELEASE
Maven: org.springframework.boot:spring-boot-starter:2.1.17.RELEASE
Maven: org.springframework.boot:spring-boot-starter-aop:2.1.17.RELEASE
Maven: org.springframework.boot:spring-boot-starter-data-jpa:2.1.17.RELEASE
Maven: org.springframework.boot:spring-boot-starter-freemarker:2.1.17.RELEASE
Maven: org.springframework.boot:spring-boot-starter-jdbc:2.1.17.RELEASE
Maven: org.springframework.boot:spring-boot-starter-json:2.1.17.RELEASE
Maven: org.springframework.boot:spring-boot-starter-logging:2.1.17.RELEASE
Maven: org.springframework.boot:spring-boot-starter-test:2.1.17.RELEASE
Maven: org.springframework.boot:spring-boot-starter-thymeleaf:2.1.17.RELEASE
Maven: org.springframework.boot:spring-boot-starter-tomcat:2.1.17.RELEASE
Maven: org.springframework.boot:spring-boot-starter-web:2.1.17.RELEASE
Maven: org.springframework.boot:spring-boot-test:2.1.17.RELEASE
Maven: org.springframework.boot:spring-boot-test-autoconfigure:2.1.17.RELEASE
Maven: org.springframework.data:spring-data-commons:2.1.20.RELEASE
Maven: org.springframework.data:spring-data-jpa:2.1.20.RELEASE
Maven: org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE
Maven: org.springframework.plugin:spring-plugin-metadata:1.2.0.RELEASE
Maven: org.springframework.security:spring-security-config:5.1.12.RELEASE
Maven: org.springframework.security:spring-security-core:5.1.12.RELEASE
Maven: org.springframework.security:spring-security-crypto:5.1.12.RELEASE
Maven: org.springframework.security:spring-security-web:5.1.12.RELEASE
Maven: org.springframework:spring-aop:5.1.18.RELEASE
Maven: org.springframework:spring-aspects:5.1.18.RELEASE
Maven: org.springframework:spring-beans:5.1.18.RELEASE
Maven: org.springframework:spring-context:5.1.18.RELEASE
Maven: org.springframework:spring-context-support:5.1.18.RELEASE
Maven: org.springframework:spring-core:5.1.18.RELEASE
Maven: org.springframework:spring-expression:5.1.18.RELEASE
Maven: org.springframework:spring-jcl:5.1.18.RELEASE
Maven: org.springframework:spring-jdbc:5.1.18.RELEASE
Maven: org.springframework:spring-orm:5.1.18.RELEASE
Maven: org.springframework:spring-test:5.1.18.RELEASE
Maven: org.springframework:spring-tx:5.1.18.RELEASE
Maven: org.springframework:spring-web:5.1.18.RELEASE
Maven: org.springframework:spring-webmvc:5.1.18.RELEASE
Maven: org.thymeleaf.extras:thymeleaf-extras-java8time:3.0.4.RELEASE
Maven: org.thymeleaf:thymeleaf:3.0.11.RELEASE
Maven: org.thymeleaf:thymeleaf-spring5:3.0.11.RELEASE
Maven: org.unbescape:unbescape:1.1.6.RELEASE
Maven: org.xmlunit:xmlunit-core:2.6.4
Maven: org.yaml:snakeyaml:1.23
Maven: redis.clients:jedis:2.9.3
Maven: stax:stax-api:1.0.1
Maven: xalan:xalan:2.6.0
Maven: xerces:xercesImpl:2.9.1
Maven: xml-apis:xml-apis:1.4.01
Maven: xml-apis:xml-apis-ext:1.3.04

**Comment by ricky0149** [comment]
<img width="1709" alt="image" src="https://user-images.githubusercontent.com/125142644/218267672-c5eb0b86-a724-499e-8306-8093838a1fd0.png">
