### ISSUE TITLE
设计数据报表时，使用统计函数=DBSUM，导致预览页面展示空白

### ISSUE THREAD

**Issue by xbqn** [jeecgboot/JimuReport#1806]
##### 问题描述：设计数据报表时，我通过统计函数=DBSUM来合计值，开始理解错误，我在单元格内录入表达式为=DBSUM(J3)，J3是我的数据列，保存后，预览时，整个页面显示为空白。后来我把表达式在单元格内清空后，再次保存、预览还是显示空白。

经过问题跟踪，发现数据报表保存是，没有根据单元格内的内容清空jimu_report表的JSON_STR的dbexps值，每次加表达式都是累加，我即使在界面上删掉表达式，表中仍然有之前的表达式内容。

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/22489956/c8df2b95-15c7-4c19-8332-7fb9345984f8)

jimu_report表的JSON_STR的dbexps值为"dbexps":["=DBSUM(H3)","=DBSUM(J3)"]

后台报错信息为：15:57:08.873 [http-nio-8080-exec-43] ERROR o.j.m.j.d.a.a - [a,401] - null
java.lang.NullPointerException: null
	at org.jeecg.modules.jmreport.desreport.model.JmExpression.getExpMapByList(JmExpression.java:121)
	at org.jeecg.modules.jmreport.desreport.service.a.e.getDataById(JimuReportServiceImpl.java:557)
	at org.jeecg.modules.jmreport.desreport.service.a.e.show(JimuReportServiceImpl.java:3733)
	at org.jeecg.modules.jmreport.desreport.service.a.e$$FastClassBySpringCGLIB$$4daca651.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.jeecg.modules.jmreport.desreport.service.a.e$$EnhancerBySpringCGLIB$$3bb0fe4f.show(<generated>)
	at org.jeecg.modules.jmreport.desreport.a.a.a(DesignReportController.java:399)
	at jdk.internal.reflect.GeneratedMethodAccessor1166.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)

##### 重现步骤：
设计数据报表时，我通过统计函数=DBSUM来合计值，开始我在单元格内录入表达式为=DBSUM(J3)，J3是我的数据列，保存后，预览时，整个页面显示为空白。后来我把表达式在单元格内清空后，再次保存、预览还是显示空白

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录 ty
