### ISSUE TITLE
导出excel空指针异常

### ISSUE THREAD

**Issue by cycyong** [jeecgboot/JimuReport#1986]
##### 问题描述：
在本地导出excel没有问题，但是部署到服务器上导出文档或样例文档都导出异常，500错误，能生成excel，但是excel里面是这样的
后台爆出空指针错误。导出pdf正常
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/62684541/2f70b158-f947-47e1-be2e-bc8362a94e9f)
![image](https://github.com/jeecgboot/JimuReport/assets/62684541/0b5bc1fa-2514-4417-a74a-89e5e7b753d2)
![image](https://github.com/jeecgboot/JimuReport/assets/62684541/fc15d70e-e0eb-468c-a843-7c93be32b340)

`
16:21:08.594 [http-nio-20712-exec-5] INFO  o.j.m.j.d.a.a - [a,637] -  JmReport Base Config JSON : org.jeecg.modules.jmreport.config.JmReportBaseConfig$$EnhancerBySpringCGLIB$$ca916bd0@2567b5bd
16:21:08.594 [http-nio-20712-exec-5] INFO  o.j.m.j.d.a.a - [a,638] - freemarker base:
16:21:08.595 [http-nio-20712-exec-5] INFO  o.j.m.j.d.a.a - [a,639] - freemarker customPrePath: /report
16:21:08.964 [http-nio-20712-exec-4] INFO  o.j.m.j.d.a.a - [a,396] - --------进入show方法-----------, id = 859334904232415232
16:21:08.985 [http-nio-20712-exec-4] INFO  o.j.m.j.d.s.a.e - [getDataById,271] - ------报表【A01】，查询的sql: select *  from gc_payerror_result_m
16:21:08.988 [http-nio-20712-exec-4] INFO  o.j.m.j.d.s.a.e - [getDataById,311] - ------数据源 dbSourceKey:【856783990990180352】
16:21:10.399 [http-nio-20712-exec-2] INFO  o.j.m.j.d.a.a - [b,1178] - ===========exportAllExcelStream 执行导出EXCEL action ==========
16:21:10.440 [http-nio-20712-exec-2] INFO  o.j.m.j.d.s.a.e - [getDataById,271] - ------报表【A01】，查询的sql: select *  from gc_payerror_result_m
16:21:10.443 [http-nio-20712-exec-2] INFO  o.j.m.j.d.s.a.e - [getDataById,311] - ------数据源 dbSourceKey:【856783990990180352】
16:21:10.468 [http-nio-20712-exec-2] ERROR c.j.c.s.h.GlobalExceptionHandler - [handleRuntimeException,82] - 请求地址'/jmreport/exportAllExcelStream',发生未知异常.
java.lang.NullPointerException: null
        at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
        at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
        at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
        at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
        at sun.font.SunFontManager$2.run(SunFontManager.java:431)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.SunFontManager.<init>(SunFontManager.java:376)
        at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
        at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
        at java.awt.Font.getFont2D(Font.java:491)
        at java.awt.Font.canDisplayUpTo(Font.java:2060)
        at java.awt.font.TextLayout.singleFont(TextLayout.java:470)
        at java.awt.font.TextLayout.<init>(TextLayout.java:531)
        at org.apache.poi.ss.util.SheetUtil.getDefaultCharWidth(SheetUtil.java:273)
        at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.<init>(AutoSizeColumnTracker.java:117)
        at org.apache.poi.xssf.streaming.SXSSFSheet.<init>(SXSSFSheet.java:82)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.createAndRegisterSXSSFSheet(SXSSFWorkbook.java:684)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:705)
        at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:587)
        at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:266)
        at org.jeecg.modules.jmreport.desreport.service.a.k.exportExcel(JmReportExportExcelImpl.java:130)
        at org.jeecg.modules.jmreport.desreport.a.a.b(DesignReportController.java:1190)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
`

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by cycyong** [comment]
集成若依微服务版本，在ubuntu上新建一个新报表导出都是500的错误

**Comment by cycyong** [comment]
初步考虑是字体问题，有没有什么解决的办法？

**Comment by zhangdaiscott** [comment]
你引入字体依赖包了吗

**Comment by zhangdaiscott** [comment]
我们在linux centos下部署都没有问题

**Comment by cycyong** [comment]
jimureport-font，是指这个包吗，它里面只有一个字体

**Comment by cycyong** [comment]
> 我们在linux centos下部署都没有问题

我的服务器是ubuntu

**Comment by cycyong** [comment]
> jimureport-font，是指这个包吗，它里面只有一个字体

![image](https://github.com/jeecgboot/JimuReport/assets/62684541/d1f00105-4724-45ff-ba4c-c3da36a5b73f)

**Comment by cycyong** [comment]
> jimureport-font，是指这个包吗，它里面只有一个字体

![image](https://github.com/jeecgboot/JimuReport/assets/62684541/d1f00105-4724-45ff-ba4c-c3da36a5b73f)

**Comment by zhangdaiscott** [comment]
看看是不是需要装中文字体
