### ISSUE TITLE
SQL数据集使用 CALL proc_sys_role(${pageNo}, ${pageSize}) 调用存储过程，提示：查询超时

### ISSUE THREAD

**Issue by vincent-shi** [jeecgboot/JimuReport#2068]
##### 版本号：
1.5.8 （ruoyi vue集成）

##### 问题描述：
数据源为SQLSERVER数据库，SQL数据集使用 CALL proc_sys_role(${pageNo}, ${pageSize}) 调用存储过程，报表预览界面报错：
CallableStatementCallback; SQL [{CALL test_proc('2022-01-01','2023-10-01')}]; 查询超时。; nested exception is java.sql.SQLTimeoutException: 查询超时。

测试了下，超时时间为60秒，查看了相关文档，没有找到可配置相关超时时间的地方，请问该如何处理

##### 错误日志&截图：
org.springframework.dao.QueryTimeoutException: CallableStatementCallback; SQL [{CALL test_proc('2022-01-01','2023-10-01')}]; 查询超时。; nested exception is java.sql.SQLTimeoutException: 查询超时。
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:76)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:1206)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:1220)
	at org.jeecg.modules.jmreport.dyndb.b.a(JmreportDynamicDbUtil.java:453)
	at org.jeecg.modules.jmreport.desreport.service.a.e.getDataById(JimuReportServiceImpl.java:289)
	at org.jeecg.modules.jmreport.desreport.service.a.e.show(JimuReportServiceImpl.java:3733)
	at org.jeecg.modules.jmreport.desreport.service.a.e$$FastClassBySpringCGLIB$$4daca651.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
	at org.jeecg.modules.jmreport.desreport.service.a.e$$EnhancerBySpringCGLIB$$89fc474d.show(<generated>)
	at org.jeecg.modules.jmreport.desreport.a.a.a(DesignReportController.java:399)
        ......

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
数据源配置地方

**Comment by vincent-shi** [comment]
> 数据源配置地方

请问你说的是数据源配置连接字符串里面？那里控制的是连接超时时间，不是语句的执行超时时间吧

**Comment by vincent-shi** [comment]
![image](https://github.com/jeecgboot/JimuReport/assets/52314591/c7c01a3b-bff5-483a-b8e0-138df3c767fa)

这种配置是不生效的
@zhangdaiscott
