### ISSUE TITLE
SQL数据集使用存储过程，由于数据库查询耗时较长，报表预览界面提示：查询超时

### ISSUE THREAD

**Issue by vincent-shi** [jeecgboot/JimuReport#2069]
##### 版本号：
1.5.8 （ruoyi vue集成）

##### 问题描述：
**issue #2068 有提，但是问题未解决，issue被关闭，不知道当前issue是否违规**
数据源为SQLSERVER数据库，SQL数据集使用 CALL proc_sys_role(${pageNo}, ${pageSize}) 调用存储过程，报表预览界面报错：
CallableStatementCallback; SQL [{CALL test_proc('2022-01-01','2023-10-01')}]; 查询超时。; nested exception is java.sql.SQLTimeoutException: 查询超时。

测试了下，超时时间为60秒，查看了相关文档，没有找到可配置相关超时时间的地方，请问该如何处理

##### 错误日志&截图：
org.springframework.dao.QueryTimeoutException: CallableStatementCallback; SQL [{CALL test_proc('2022-01-01','2023-10-01')}]; 查询超时。; nested exception is java.sql.SQLTimeoutException: 查询超时。
at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:76)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:1206)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:1220)
at org.jeecg.modules.jmreport.dyndb.b.a(JmreportDynamicDbUtil.java:453)
at org.jeecg.modules.jmreport.desreport.service.a.e.getDataById(JimuReportServiceImpl.java:289)
at org.jeecg.modules.jmreport.desreport.service.a.e.show(JimuReportServiceImpl.java:3733)
at org.jeecg.modules.jmreport.desreport.service.a.e$$FastClassBySpringCGLIB$$4daca651.invoke()
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
at org.jeecg.modules.jmreport.desreport.service.a.e$$EnhancerBySpringCGLIB$$89fc474d.show()
at org.jeecg.modules.jmreport.desreport.a.a.a(DesignReportController.java:399)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by vincent-shi** [comment]
@zhangdaiscott  在数据源配置的地方配置连接字符串的Connection Timeout 并不能解决问题，issue中提及的错误是执行语句超时导致，不是数据库连接的超时时间

**Comment by zhangdaiscott** [comment]
先升级到最新版

**Comment by vincent-shi** [comment]
> 先升级到最新版

请问是升级之后再通过连接字符串配置 Connection Timeout 么？

**Comment by vincent-shi** [comment]
或者说是通过项目中的.yml某个节点配置？
我搜索issue历史，找到 #1257  与我的情况类似，但是看到被归集到 #138  列为暂不支持功能了，由于时间比较久，不清楚现在是否开放支持了

**Comment by zhangdaiscott** [comment]
升级到最新版，再通过配置
![image](https://github.com/jeecgboot/JimuReport/assets/3162115/7c04b268-3116-4776-b319-cbef48849c46)

**Comment by vincent-shi** [comment]
> 升级到最新版，再通过配置 ![image](https://user-images.githubusercontent.com/3162115/275382332-7c04b268-3116-4776-b319-cbef48849c46.png)

非常感谢你的回复。我试试

**Comment by vincent-shi** [comment]
@zhangdaiscott 经测试，该配置jimureport 1.5.8 版本已支持。
非常感谢
