### ISSUE TITLE
数据库数据值存在反斜杠 \字符时报错

### ISSUE THREAD

**Issue by panquanlin** [jeecgboot/JimuReport#2152]
##### 版本号：
1.6.4

##### 问题描述：
数据库数据值为：反斜杠（\）时报错
##### 错误日志&截图：
如数据库数据值为：内退\待审批 ;报错如下：
2023-11-10 11:53:21.709 [http-nio-9012-exec-8] ERROR org.jeecg.modules.jmreport.desreport.a.a - unclosed string : 待
com.alibaba.fastjson.JSONException: unclosed string : 待
	at com.alibaba.fastjson.parser.JSONLexerBase.scanString(JSONLexerBase.java:1003)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:495)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:581)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:581)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:581)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1430)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1390)
	at com.alibaba.fastjson.JSON.parse(JSON.java:181)
	at com.alibaba.fastjson.JSON.parse(JSON.java:191)
	at com.alibaba.fastjson.JSON.parse(JSON.java:147)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:252)
	at org.jeecg.modules.jmreport.desreport.render.a.a.b.a(BaseBaseRenderStrategy.java:183)
	at org.jeecg.modules.jmreport.desreport.render.a.a.b.c(BaseBaseRenderStrategy.java:52)
	at org.jeecg.modules.jmreport.desreport.service.a.e.a(JimuReportServiceImpl.java:4253)
	at org.jeecg.modules.jmreport.desreport.service.a.e.show(JimuReportServiceImpl.java:4152)
	at org.jeecg.modules.jmreport.desreport.service.a.e$$FastClassBySpringCGLIB$$4daca651.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at org.jeecg.modules.jmreport.desreport.service.a.e$$EnhancerBySpringCGLIB$$95e87e69.show(<generated>)
	at org.jeecg.modules.jmreport.desreport.a.a.a(DesignReportController.java:391)
	at sun.reflect.GeneratedMethodAccessor287.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)

##### 重现步骤：

修改数据库的值输入反斜杠：\，预览时就会出现报错提示语

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
为什么会出现这种数据

**Comment by panquanlin** [comment]
> 为什么会出现这种数据

客户有时候会录入反斜杠：\的要求

**Comment by panquanlin** [comment]
好的，感谢！
