### ISSUE TITLE
spring boot 版本不兼容

### ISSUE THREAD

**Issue by chengliangcode** [jeecgboot/JimuReport#2154]
spring boot 版本不兼容

        <dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>jimureport-spring-boot-starter</artifactId>
            <version>1.6.4</version>
        </dependency>
        
 为什么在依赖里定义spring-boot 2.7.10，运行不起来，缺少一个jackson的异常类，
-----------------------------------------------
尝试了下2.5.15可以

**Comment by zhangdaiscott** [comment]
jackson版本号冲突？

**Comment by chengliangcode** [comment]
可能是，但我没有进一步分析，你可以运行一下试试异常是：

**Comment by chengliangcode** [comment]
可能是，但我没有进一步分析，你可以运行一下试试异常是：
```

Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/exc/StreamWriteException
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_341]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_341]
	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_341]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:467) ~[spring-core-5.3.26.jar:5.3.26]
	... 84 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.exc.StreamWriteException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_341]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_341]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[na:1.8.0_341]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_341]
	... 88 common frames omitted
```

**Comment by zhangdaiscott** [comment]
自己排查依赖版本冲突即可
