### ISSUE TITLE
导出图表报错 NumberFormatException

### ISSUE THREAD

**Issue by CrackerClay** [jeecgboot/JimuReport#2236]
##### 版本号：
1.6.5

##### 问题描述：
因图表高度导致导出报错，手工到数据库修正数据后可恢复导出

##### 错误日志&截图：
java.lang.NumberFormatException: For input string: "646.984"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.jeecg.modules.jmreport.desreport.service.a.l.a(JmReportExportExcelImpl.java:1894)
	at org.jeecg.modules.jmreport.desreport.service.a.l.a(JmReportExportExcelImpl.java:681)
	at org.jeecg.modules.jmreport.desreport.service.a.l.a(JmReportExportExcelImpl.java:183)
	at org.jeecg.modules.jmreport.desreport.service.a.l.exportExcel(JmReportExportExcelImpl.java:146)

![image](https://github.com/jeecgboot/JimuReport/assets/29972069/76457004-8bec-45ad-b6b2-bd02a8be4140)

##### 重现步骤：
1. 拖拽图表组件
2. 任意放大

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
录个视频或者提供

请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by CrackerClay** [comment]
[导出报错.json](https://github.com/jeecgboot/JimuReport/files/13522816/default.json)

**Comment by zhangdaiscott** [comment]
升级到临时版本

```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.6.6-beta2</version>
</dependency>
```
