### ISSUE TITLE
mysql 存储过程调用出错

### ISSUE THREAD

**Issue by wuyb66** [jeecgboot/JimuReport#2376]
##### 问题描述：
mysql 存储过程调用出错， CALL GetInspectResult('${in_task_id}‘)，不使用变量，直接传值调用正常

##### 错误日志&截图：
2024-01-17 15:00:54.708 [http-nio-8085-exec-3] INFO  org.jeecg.modules.jmreport.dyndb.b:462 - 存储过程替换前的sql：：：{CALL GetInspectResult(':in_task_id‘)}
2024-01-17 15:00:54.709 [http-nio-8085-exec-3] INFO  org.jeecg.modules.jmreport.dyndb.b:463 - 存储过程替换前参数：：：{in_task_id=2a9280647c514d8ab43546efbe4b0b3b}
2024-01-17 15:00:54.709 [http-nio-8085-exec-3] INFO  org.jeecg.modules.jmreport.dyndb.b:469 - 存储过程替换后的sql：：：{CALL GetInspectResult(':in_task_id‘)}
2024-01-17 15:00:54.709 [http-nio-8085-exec-3] INFO  org.jeecg.modules.jmreport.dyndb.b:470 - 存储过程替换后的参数：：：[]
2024-01-17 15:00:54.720 [http-nio-8085-exec-3] ERROR org.jeecg.modules.jmreport.dyndb.b:548 - CallableStatementCallback; bad SQL grammar [{CALL GetInspectResult(':in_task_id‘)}]; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '':in_task_id‘)' at line 1
org.springframework.jdbc.BadSqlGrammarException: CallableStatementCallback; bad SQL grammar [{CALL GetInspectResult(':in_task_id‘)}]; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '':in_task_id‘)' at line 1
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:1206)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:1220)
	at org.jeecg.modules.jmreport.dyndb.b.c(JmreportDynamicDbUtil.java:472)
	at org.jeecg.modules.jmreport.desreport.service.a.j.parseReportSql(JmReportDbServiceImpl.java:621)
	at org.jeecg.modules.jmreport.desreport.service.a.j$$FastClassBySpringCGLIB$$4daca656.invoke(<generated>)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lvdandan16** [comment]
收录  ws

**Comment by 1298191366** [comment]
你的存储过程是怎样写的，接收的值是几位？${DaoFormat.in} 发回的是多个值 即 '20','30','40',如果你接收只有一个值，肯定会报错。
![image](https://github.com/jeecgboot/JimuReport/assets/30997828/beeea901-9f6d-4928-acf8-f5eb19e6374c)

**Comment by wuyb66** [comment]
现在存储过程调用用${DaoFormat.in}可以正常工作了，如果是这样设计的，需要更新一下文档

**Comment by 1298191366** [comment]
收到

**Comment by wuyb66** [comment]
接收的值是字符串，用${param}方式报错，用${DaoFormat.in}可以正常工作，MySQL5.7
