### ISSUE TITLE
1.6.6版本，添加数据源失败

### ISSUE THREAD

**Issue by jalena** [jeecgboot/JimuReport#2378]
##### 版本号：
1.6.6

##### 问题描述：
观察日志应该是自动将 数据库链接中的&进行转码`&amp;`，以至于提前接收到`;`符号，而导致错误。

##### 错误日志&截图：
```
==============  Sql Start  ==============
Execute SQL : select * from jimu_report_data_source where ID = '8f90daf47d15d35ca6cf420748b8b9ba'
Execute Time: 1.153ms
==============  Sql  End   ==============

2024-01-18 10:50:08.378  INFO 1 --- [  XNIO-1 task-5] o.j.m.j.c.f.i.JimuLowCodeModeInterceptor : 低代码模式，拦截请求路径：/jmreport/testConnection
2024-01-18 10:50:08.381  INFO 1 --- [  XNIO-1 task-5] o.jeecg.modules.jmreport.desreport.a.a   :  local cache key: cm9vdGpkYmM6bXlzcWw6Ly8xMjcuMC4wLjE6MzMwNi9qZWVjZy1ib290P3VzZVVuaWNvZGU9dHJ1ZSZhbXA7Y2hhcmFjdGVyRW5jb2Rpbmc9VVRGLTgmYW1wO3NlcnZlclRpbWV6b25lPUdNVCUyQjhyb290
2024-01-18 10:50:08.384 ERROR 1 --- [  XNIO-1 task-5] o.jeecg.modules.jmreport.desreport.a.a   : java.sql.SQLNonTransientConnectionException: Cannot load connection class because of underlying exception: com.mysql.cj.exceptions.WrongArgumentException: Malformed database URL, failed to parse the connection string near ';characterEncoding=UTF-8&amp;serverTimezone=GMT%2B8&allowLoadLocalInfile=false'.

java.sql.SQLNonTransientConnectionException: Cannot load connection class because of underlying exception: com.mysql.cj.exceptions.WrongArgumentException: Malformed database URL, failed to parse the connection string near ';characterEncoding=UTF-8&amp;serverTimezone=GMT%2B8&allowLoadLocalInfile=false'.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111) ~[mysql-connector-j-8.0.33.jar!/:8.0.33]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98) ~[mysql-connector-j-8.0.33.jar!/:8.0.33]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90) ~[mysql-connector-j-8.0.33.jar!/:8.0.33]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64) ~[mysql-connector-j-8.0.33.jar!/:8.0.33]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:74) ~[mysql-connector-j-8.0.33.jar!/:8.0.33]
```

##### 重现步骤：
![image](https://github.com/jeecgboot/JimuReport/assets/5668673/d03fb835-b2fd-4cea-a72d-b2ddf7f3dcce)

**Comment by lvdandan16** [comment]
看看是不是你数据库的问题，我们没有遇到过这个问题

**Comment by jalena** [comment]
跟踪了下代码，前端会将&字符转义，后端就抛出这个异常了

**Comment by gaokaoli** [comment]
> 跟踪了下代码，前端会将&字符转义，后端就抛出这个异常了


请问最后你怎么解决呢，发现没有 & 就可以访问成功，但是这个bug，怎么其他项目就没有，很反常！

**Comment by jalena** [comment]
> > 跟踪了下代码，前端会将&字符转义，后端就抛出这个异常了
> 
> 请问最后你怎么解决呢，发现没有 & 就可以访问成功，但是这个bug，怎么其他项目就没有，很反常！

因为它默认处理了前端请求传过来的字符串，给转义了！

**Comment by gsy19850221** [comment]
这破项目，提了白提，都没解决实际问题
