### ISSUE TITLE
积木报表切换日期后出现异常

### ISSUE THREAD

**Issue by 199hl** [jeecgboot/JimuReport#2539]
##### 版本号：
1.6.6

##### 问题描述：
切换日期出现异常 报错500

##### 错误日志&截图：
17:25:20.205 [http-nio-8090-exec-9] ERROR c.z.f.w.e.GlobalExceptionHandler - [handleException,79] - 请求地址'/jmreport/show',发生系统异常.
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.StackOverflowError
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1082)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.jeecg.modules.jmreport.common.a.a.doFilter(JimuReportFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.zhoufeng.common.filter.RepeatableFilter.doFilter(RepeatableFilter.java:32)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:121)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at com.zhoufeng.framework.security.filter.JwtAuthenticationTokenFilter.doFilterInternal(JwtAuthenticationTokenFilter.java:44)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.StackOverflowError: null
	at java.util.regex.Pattern.clazz(Pattern.java:2562)
	at java.util.regex.Pattern.sequence(Pattern.java:2063)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.group0(Pattern.java:2905)
	at java.util.regex.Pattern.sequence(Pattern.java:2051)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.compile(Pattern.java:1696)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at org.jeecg.modules.jmreport.desreport.express.a.b(ExpressHandler.java:384)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:271)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)
	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:298)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
切换日期是什么意思

**Comment by 199hl** [comment]
我们这边的数据都是可以正常展示出来的 调用你们这边的接口的时候 出现在这问题 有些展示的数据就不会出现这个问题

**Comment by zhangdaiscott** [comment]
没明白，录个视频或者写个详细操作步骤
