### ISSUE TITLE
积木报表不支持sap的hana数据库，在多数据源的情况下怎么屏蔽hana的数据库呢

### ISSUE THREAD

**Issue by sybobi** [jeecgboot/JimuReport#2590]
##### 版本号：
1.7.4

##### 问题描述：
springboot项目集成积木报表启动时，报dbType not support，项目配置了mysql、sqlserver和sap hana三个数据库的数据源，但是hana数据库积木报表不支持，那么积木报表能否屏蔽hana数据库使用呢？

##### 错误日志&截图：
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 25 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthEndpoint]: Factory method 'healthEndpoint' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration$$EnhancerBySpringCGLIB$$8f323488]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/yjh/mushroom/shardingjdbc/configuration/ShardingJdbcDataSourceConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: dbType not support : null, url jdbc:sap://192.168.33.171:31015?reconnect=true
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:583)
	... 49 common frames omitted

##### 重现步骤：
项目配置多数据源启动
![image](https://github.com/jeecgboot/JimuReport/assets/97718113/07036d09-33fa-4f6d-8d86-4ce8c848ebca)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
可参考改文档，给积木报表分配独立的数据源：https://help.jeecg.com/jimureport/config/multdb.html

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
积木报表默认只会使用master数据源，并不会使用从属数据源。
您项目启动报dbType not support错应该不是积木报表不支持hana导致的。
可以检查下您使用的连接池是否支持hana数据库。
