### ISSUE TITLE
GBase 8s 提示user_tab_comments表不存在的问题

### ISSUE THREAD

**Issue by cqliulingbo** [jeecgboot/JimuReport#2595]
##### 版本号：
1.74

##### 问题描述：
在适配南大通用GBase 8s数据库时，因GBase 8s数据库源自Informix，故在PageAutoDialect中添加了registerDialectAlias("gbasedbt-sqli", InformixDialect.class);项目能正常运行，相应的demo也正常运行，但是在新建的时候，会提示The specified table (user_tab_comments) is not in the database，不知是何原因需要去查询这个表，informix本身是没这个表的。虽然有这个错误提示，但是不影响功能的使用

##### 错误日志&截图：
2024-04-27 19:45:57.485 [http-nio-8085-exec-8] INFO  org.jeecgframework.minidao.util.MiniDaoUtil:169 - 获取DB类型：gbasedbt-sqli，耗时：227ms
---------verify-----Token---------------
---------verify-----Token---------------
---------verify-----Token---------------
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [select table_name name,comments comments from user_tab_comments]; nested exception is java.sql.SQLException: The specified table (user_tab_comments) is not in the database.
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:713)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:738)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:794)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:209)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:216)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate$$FastClassBySpringCGLIB$$9d5423dc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate$$EnhancerBySpringCGLIB$$ee436ac5.query(<generated>)
	at org.jeecgframework.minidao.aop.MiniDaoHandler.getReturnMinidaoResult(MiniDaoHandler.java:446)
	at org.jeecgframework.minidao.aop.MiniDaoHandler.invoke(MiniDaoHandler.java:131)
	at com.sun.proxy.$Proxy71.getAllTable(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy74.getAllTable(Unknown Source)
	at org.jeecg.modules.jmreport.desreport.service.a.k.getTableNum(JmReportDbSourceServiceImpl.java:198)
	at org.jeecg.modules.jmreport.common.interceptor.pdfhelper.JimuReportPdfHelper.doPreCheck(JimuReportPdfHelper.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jeecg.modules.jmreport.a.b.c.a(JmPackLoaderUtils.java:53)
	at org.jeecg.modules.jmreport.common.interceptor.a.b.preHandle(JimuReportPdfHelperInterceptor.java)
	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:148)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:528)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:596)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.SQLException: The specified table (user_tab_comments) is not in the database.
	at com.gbasedbt.jdbc.IfxSqli.a(IfxSqli.java:3570)
	at com.gbasedbt.jdbc.IfxSqli.D(IfxSqli.java:3852)
	at com.gbasedbt.jdbc.IfxSqli.dispatchMsg(IfxSqli.java:2738)
	at com.gbasedbt.jdbc.IfxSqli.receiveMessage(IfxSqli.java:2663)
	at com.gbasedbt.jdbc.IfxSqli.executePrepare(IfxSqli.java:1290)
	at com.gbasedbt.jdbc.IfxPreparedStatement.f(IfxPreparedStatement.java:504)
	at com.gbasedbt.jdbc.IfxPreparedStatement.a(IfxPreparedStatement.java:485)
	at com.gbasedbt.jdbc.IfxPreparedStatement.<init>(IfxPreparedStatement.java:278)
	at com.gbasedbt.jdbc.IfxSqliConnect.h(IfxSqliConnect.java:6597)
	at com.gbasedbt.jdbc.IfxSqliConnect.prepareStatement(IfxSqliConnect.java:2656)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.createPreparedStatement(PreparedStatementCreatorFactory.java:235)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
	... 74 more
Caused by: java.sql.SQLException: ISAM error: no record found.
	at com.gbasedbt.util.IfxErrMsg.getSQLException(IfxErrMsg.java:409)
	at com.gbasedbt.jdbc.IfxSqli.D(IfxSqli.java:3857)
	... 86 more

##### 重现步骤：
适配过程可以参考#2581
    url: jdbc:gbasedbt-sqli://111.229.75.230:9089/jimureport:GBASEDBTSERVER=gbase351;SQLMODE=ORACLE;DB_LOCALE=zh_CN.utf8;CLIENT_LOCALE=zh_CN.utf8;IFX_LOCK_MODE_WAIT=60;
    username: gbasedbt
    password: GBase123
    driver-class-name: com.gbasedbt.jdbc.Driver
这个环境是我的一个测试环境  是公网环境 可直接使用
<dependency>
            <groupId>com.gbasedbt</groupId>
            <artifactId>gbasedbt</artifactId>
            <version>3.3.3</version>
            <scope>system</scope>
            <systemPath>${basedir}/src/main/resources/lib/gbasedbtjdbc_3.3.3_1X1_2_7ae7a4.jar</systemPath>
        </dependency>

[gbasedbtjdbc_3.3.3_1X1_2_7ae7a4.zip](https://github.com/jeecgboot/JimuReport/files/15138115/gbasedbtjdbc_3.3.3_1X1_2_7ae7a4.zip)
该附件是我使用的驱动文件

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
没适配这个数据库

**Comment by cqliulingbo** [comment]
能否在后续版本适配一下呢

**Comment by jeecgos** [comment]
暂不支持，归集：#138
