### ISSUE TITLE
报表无法正常显示，后台日志报异常

### ISSUE THREAD

**Issue by zzdxzhangzhi** [jeecgboot/JimuReport#2638]
##### 版本号：
1.7.4

##### 问题描述：
创建了一个报表，数据集，表格，sql语句都已经配置好，sql可以解析成功，并且预览数据（前10条）也正常，查询参数也配置好。
但是当实际预览整个报表时，只能显示出查询栏，查询参数的具体内容也正确，但是报表体显示不出来。查看后台日志，发现报告异常，异常见下图：

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/23204727/453de69b-1941-469a-b987-9918d9ed7853)

主要错误是这个异常：
ERROR org.jeecg.modules.jmreport.desreport.a.a:438 - String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at org.jeecg.modules.jmreport.desreport.service.a.e.a(JimuReportServiceImpl.java:5089)
        at org.jeecg.modules.jmreport.desreport.service.a.e.getDbSql(JimuReportServiceImpl.java:5949)
        at org.jeecg.modules.jmreport.desreport.service.a.e.getDataById(JimuReportServiceImpl.java:318)
        at org.jeecg.modules.jmreport.desreport.service.a.e.show(JimuReportServiceImpl.java:4320)
        at org.jeecg.modules.jmreport.desreport.service.a.e$$FastClassBySpringCGLIB$$4daca651.invoke(<generated>)

##### 重现步骤：
点击预览报表

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;

**Comment by zzdxzhangzhi** [comment]
[明细表.json](https://github.com/jeecgboot/JimuReport/files/15343840/default.json)
附件是报表导出的配置json文件

**Comment by zzdxzhangzhi** [comment]
报表设计配置文件有用吗？

**Comment by zzdxzhangzhi** [comment]
> 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
[明细表报表配置.json](https://github.com/jeecgboot/JimuReport/files/15372112/default.json)

**Comment by zhangdaiscott** [comment]
什么环境？

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
1.7.4是有bug，您升级到1.7.8应该就好了
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.7.8</version>
</dependency>
```
