### ISSUE TITLE
预览报表时报错 Could not initialize class org.jeecg.modules.jmreport.desreport.express.ExpressUtil

### ISSUE THREAD

**Issue by xzz19930108** [jeecgboot/JimuReport#2708]
##### 版本号：
1.5.3

##### 问题描述：
新建时没有问题 预览时报错

##### 错误日志&截图：
Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.jeecg.modules.jmreport.desreport.express.ExpressUtil
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.jeecg.modules.jmreport.desreport.express.ExpressUtil
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1082)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
建议用最新版
