### ISSUE TITLE
项目启动报错 ConflictingBeanDefinitionException

### ISSUE THREAD

**Issue by lijing1853** [jeecgboot/JimuReport#2730]
##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/173685500/40d3c6c3-b6dc-4055-8f55-f98f7856a8c4)

Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'functionRender' for bean class [org.jeecg.modules.jmreport.desreport.render.a.b.c] conflicts with existing, non-compatible bean definition of same name and class [org.jeecg.modules.jmreport.desreport.render.a.b.b]
        at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:349)
        at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:287)
        at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:128)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:295)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:249)
        at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:599)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by lijing1853** [comment]
该问题已经解决，原因是购买了商业版，且同时依赖了商业版的包和 开原版的包，
应该是商业版的替换掉开原版的依赖包，
