### ISSUE TITLE
离线配置批量导出、批量打印提示During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by AXXZSTHL** [jeecgboot/JimuReport#2905]
##### 问题描述：
离线配置批量导出、批量打印提示During handling of the above exception, another exception occurred:

##### 错误日志&截图：
[file.txt](https://github.com/user-attachments/files/16667994/file.txt)

##### 重现步骤：
[32mINFO[0m:     Started server process [[36m7536[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://127.0.0.1:16065[0m (Press CTRL+C to quit)
下载目录:D:\www\JimuReport\JimuReport v1.7.6\静默打印插件_接口导出功能\downloads\
积木报表地址:http://10.8.5.181:8888/jmreport/view/
INFO:     127.0.0.1:65317 - "POST /export/report HTTP/1.0" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "urllib3\connection.py", line 198, in _new_conn
  File "urllib3\util\connection.py", line 60, in create_connection
  File "socket.py", line 954, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 793, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1099, in _validate_conn
  File "urllib3\connection.py", line 616, in connect
  File "urllib3\connection.py", line 205, in _new_conn
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001F35A6B0850>: Failed to resolve 'googlechromelabs.github.io' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 847, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='googlechromelabs.github.io', port=443): Max retries exceeded with url: /chrome-for-testing/latest-patch-versions-per-build.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F35A6B0850>: Failed to resolve 'googlechromelabs.github.io' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "webdriver_manager\core\http.py", line 32, in get
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='googlechromelabs.github.io', port=443): Max retries exceeded with url: /chrome-for-testing/latest-patch-versions-per-build.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F35A6B0850>: Failed to resolve 'googlechromelabs.github.io' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 69, in __call__
  File "fastapi\applications.py", line 1054, in __call__
  File "starlette\applications.py", line 123, in __call__
  File "starlette\middleware\errors.py", line 186, in __call__
  File "starlette\middleware\errors.py", line 164, in __call__
  File "starlette\middleware\cors.py", line 83, in __call__
  File "starlette\middleware\exceptions.py", line 62, in __call__
  File "starlette\_exception_handler.py", line 64, in wrapped_app
  File "starlette\_exception_handler.py", line 53, in wrapped_app
  File "starlette\routing.py", line 758, in __call__
  File "starlette\routing.py", line 778, in app
  File "starlette\routing.py", line 299, in handle
  File "starlette\routing.py", line 79, in app
  File "starlette\_exception_handler.py", line 64, in wrapped_app
  File "starlette\_exception_handler.py", line 53, in wrapped_app
  File "starlette\routing.py", line 74, in app
  File "fastapi\routing.py", line 278, in app
  File "fastapi\routing.py", line 191, in run_endpoint_function
  File "main.py", line 88, in export_report
  File "exporter.py", line 195, in auto_export_4_api
  File "exporter.py", line 224, in auto_export
  File "exporter.py", line 359, in build_web_driver
  File "webdriver_manager\chrome.py", line 40, in install
  File "webdriver_manager\core\manager.py", line 35, in _get_driver_binary_path
  File "webdriver_manager\core\driver_cache.py", line 105, in find_driver
  File "webdriver_manager\core\driver_cache.py", line 152, in get_cache_key_driver_version
  File "webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
  File "webdriver_manager\drivers\chrome.py", line 59, in get_latest_release_version
  File "webdriver_manager\core\http.py", line 35, in get
requests.exceptions.ConnectionError: Could not reach host. Are you offline?

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by jeecgos** [comment]
看报错应该是谷歌浏览器的驱动没下载下来，请确保你的网络能正常访问谷歌的网络

**Comment by AXXZSTHL** [comment]
我的是内网电脑环境，可以用python正常跑selenium的测试，你指的缺哪个驱动

**Comment by zhangdaiscott** [comment]
后面我们会出插件版，你应该装的有问题

**Comment by AXXZSTHL** [comment]
这个功能不需要再单独购买吧
