### ISSUE TITLE
导出excel数据文件失败

### ISSUE THREAD

**Issue by SunYoung06** [jeecgboot/JimuReport#3005]
##### 版本号：

1.7.5
##### 问题描述：

使用导出数据功能时，提示导出失败，
##### 错误日志&截图：
2024-09-23 16:00:16.905 ERROR 2949339 --- [http-nio-8185-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: java.nio.file.NoSuchFileException: /tmp/d2c7e28c-6d9f-47c9-a03f-8214d037b585/poifiles/poi-sxssf-sheet7710475387324331036.xml] with root cause

java.nio.file.NoSuchFileException: /tmp/**d2c7e28c-6d9f-47c9-a03f-8214d037b585**/poifiles/poi-sxssf-sheet7710475387324331036.xml
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.createFile(Files.java:632)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
	at java.nio.file.Files.createTempFile(Files.java:852)
	at org.apache.poi.util.DefaultTempFileCreationStrategy.createTempFile(DefaultTempFileCreationStrategy.java:102)
	at org.apache.poi.util.TempFile.createTempFile(TempFile.java:67)
	at org.apache.poi.xssf.streaming.SheetDataWriter.createTempFile(SheetDataWriter.java:100)
	at org.apache.poi.xssf.streaming.SheetDataWriter.<init>(SheetDataWriter.java:74)
	at org.apache.poi.xssf.streaming.SheetDataWriter.<init>(SheetDataWriter.java:84)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheetDataWriter(SXSSFWorkbook.java:387)
	at org.apache.poi.xssf.streaming.SXSSFSheet.<init>(SXSSFSheet.java:103)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createAndRegisterSXSSFSheet(SXSSFWorkbook.java:694)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:712)
	at org.jeecg.modules.jmreport.desreport.service.a.l.a(JmReportExportExcelImpl.java:599)
	at org.jeecg.modules.jmreport.desreport.service.a.l.a(JmReportExportExcelImpl.java:278)
	at org.jeecg.modules.jmreport.desreport.service.a.l.exportExcel(JmReportExportExcelImpl.java:140)
	at org.jeecg.modules.jmreport.desreport.a.a.b(DesignReportController.java:1314)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:517)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.jeecg.modules.jmreport.common.a.a.doFilter(JimuReportFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:383)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.lang.Thread.run(Thread.java:750)

![image](https://github.com/user-attachments/assets/6dc67994-3fb9-47a4-b6ac-01fba43ed2f4)

##### 重现步骤：

根据报错日志，猜测是向/tmp目录读取临时文件时，没有找到临时文件导致的，但是这个文件是积木报表临时生成的，问题1：是写入时失败，没有报错导致后面读取失败吗？
一开始怀疑是路径权限问题：程序向/tmp目录下写临时文件失败导致的，测试环境收回写入权限后，可以必现，
但是产线的环境中启动程序的权限/tmp目录是有读写权限的，可以随意创建文件或目录，随即排除了/tmp目录无法写入的问题，
再后来通过对比产线和测试环境的失败日志发现，产线的错误日志比测试环境多了一层目录，问题2：这个目录不知道是否有影响？

![c201973264b44c6af10e480a6ee31831](https://github.com/user-attachments/assets/feceb2c1-0934-4c9f-ab4b-2a54d33a01a7)

问题3： 这个临时目录是否可以配置？是否能放在别的目录？

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
什么系统

**Comment by SunYoung06** [comment]
linux 系统

**Comment by SunYoung06** [comment]
产线多的这个目录：d2c7e28c-6d9f-47c9-a03f-8214d037b585 是什么情况？

**Comment by zhangdaiscott** [comment]
是不是需要临时目录的权限，可能你给的权限不够

**Comment by jeecgos** [comment]
操作系统：centos7.9 导出exce正常，未能复现您的问题。看您的问题堆栈应该是你的服务器权限的问题。
![QQ_1728878974511](https://github.com/user-attachments/assets/93f82b53-8772-43cd-ab6c-18f28d7caeff)

**Comment by hoperunChen** [comment]
操作系统：centos7.9 导出exce正常，未能复现您的问题。看您的问题堆栈应该是你的服务器权限的问题。
![QQ_1728878974511](https://github.com/user-attachments/assets/93f82b53-8772-43cd-ab6c-18f28d7caeff)

**Comment by HoHo1** [comment]
我也遇到这个问题,请问是什么原因,解决了么
