### ISSUE TITLE
第一次设计视图保存后，第二次保存 报错

### ISSUE THREAD

**Issue by tw20510946** [jeecgboot/JimuReport#3279]
##### 版本号：
190~191都有问题

##### 问题描述：
第一次设计视图保存后，第二次保存 报错

##### 错误日志&截图：
}"},"18":{"text":"#{OA01.field0080}"},"19":{"text":"#{OA01.field0098}"},"20":{"text":"#{OA01.field0111}"},"21":{"text":"#{OA01.field0115}"},"22":{"text":"#{OA01.field0113}"},"23":{"text":"#{OA01.field0114}"},"24":{"text":"#{OA01.field0059}"},"25":{"text":"#{OA01.field0112}"},"26":{"text":"#{OA01.field0088}"},"27":{"text":"#{OA01.field0092}"},"28":{"text":"#{OA01.field0084}"},"29":{"text":"#{OA01.field0085}"},"30":{"text":"#{OA01.field0086}"},"31":{"text":"#{OA01.field0091}"},"32":{"text":"#{OA01.field0093}"},"33":{"text":"#{OA01.field0093}"},"34":{"text":"#{OA01.field0133}"}}},"2":{"cells":{"17":{}}},"len":199},"cols":{"len":100},"validations":[],"autofilter":{},"dbexps":[],"dicts":[],"loopBlockList":[],"zonedEditionList":[],"fixedPrintHeadRows":[],"fixedPrintTailRows":[],"rpbar":{"show":true,"pageSize":"","btnList":[]},"hiddenCells":[],"hidden":{"rows":[],"cols":[]},"fillFormInfo":{"layout":{"direction":"horizontal","width":200,"height":45}},"recordSubTableOrCollection":{"group":[],"record":[],"range":[]},"background":false,"area":{"sri":5,"sci":3,"eri":5,"eci":3,"width":100,"height":25},"dataRectWidth":3500,"excel_config_id":"1028898611166023680","pyGroupEngine":false,"querySetting":{"izOpenQueryBar":false,"izDefaultQuery":true},"submitHandlers":[],"queryFormSetting":{"useQueryForm":false,"dbKey":"","idField":""}}
        at com.alibaba.fastjson.parser.JSONLexerBase.scanSymbolUnQuoted(JSONLexerBase.java:834)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:298)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1430)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1390)
        at com.alibaba.fastjson.JSON.parse(JSON.java:181)
        at com.alibaba.fastjson.JSON.parse(JSON.java:191)
        at com.alibaba.fastjson.JSON.parse(JSON.java:147)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:252)
        at org.jeecg.modules.jmreport.common.interceptor.pdfhelper.JimuReportPdfHelper.doPreCheck(JimuReportPdfHelper.java:192)
        at sun.reflect.GeneratedMethodAccessor252.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jeecg.modules.jmreport.plugin.utils.c.a(JmPackLoaderUtils.java:53)
        at org.jeecg.modules.jmreport.common.interceptor.a.b.preHandle(JimuReportPdfHelperInterceptor.java)
        at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:148)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at com.jeecg.modules.jmreport.config.JimuReportSysSwitchFilter.doFilter(JimuReportSysSwitchFilter.java:57)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.jeecg.modules.jmreport.common.a.a.doFilter(JimuReportFilter.java:26)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:106)
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:97)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at com.jeecg.modules.jmreport.config.ApiSecurityConfigFilter.doFilter(ApiSecurityConfigFilter.java:33)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:223)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.session.ForceEagerSessionCreationFilter.doFilterInternal(ForceEagerSessionCreationFilter.java:45)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.session.ForceEagerSessionCreationFilter.doFilterInternal(ForceEagerSessionCreationFilter.java:45)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

##### 重现步骤：
oracle 数据库， 字段比较多，30多个。
第一次保存ok，第二次修改再保存，就报错。

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
升级sql都执行了吗

**Comment by tw20510946** [comment]
> 升级sql都执行了吗

我官网 重新下载的“JimuReport v1.9.1版本带仪表盘大屏(绿色免安装版).zip”

没发现什么 升级sql呀。 全新部署，全新数据库。

**Comment by zhangdaiscott** [comment]
录个视频看看

**Comment by tw20510946** [comment]
> 录个视频看看

一会，我反馈到“JimuReport交流群③”。

**Comment by zhangdaiscott** [comment]
视频发链接

**Comment by tw20510946** [comment]
![image](https://github.com/user-attachments/assets/750f50e0-d785-4d2c-b307-fc789e3e7760)

[log.txt](https://github.com/user-attachments/files/18163251/log.txt)


提供一个截图，和完整日志。

**Comment by zhangdaiscott** [comment]
发图有什么用

**Comment by tw20510946** [comment]
> 发图有什么用

页面上什么反应没有。
只有后台报错。
录视频的话，需要看哪部分。

**Comment by zhangdaiscott** [comment]
你数据库肯定是老的，没有执行增量升级SQL

**Comment by tw20510946** [comment]
![image](https://github.com/user-attachments/assets/78df8406-3f23-4fda-9061-bf4442bb9d33)

“JimuReport v1.9.1版本带仪表盘大屏(绿色免安装版).zip” 里边自带的 脚本执行完，还要执行增量么。

**Comment by tw20510946** [comment]
![image](https://github.com/user-attachments/assets/194e39cf-90b9-49c1-a775-a172e353caef)


![image](https://github.com/user-attachments/assets/95b1e6dc-e54d-4531-aa4a-d0dab8d35220)

**Comment by zhangdaiscott** [comment]
我看了你群里的视频，默认脚本哪有你演示的报表

**Comment by tw20510946** [comment]
> 我看了你群里的视频，默认脚本哪有你演示的报表

我演示的，是我新建的。
第一次能保存，能看，再编辑就报错。
三群已经有和我遇到一样问题的了。

**Comment by zhangdaiscott** [comment]
甭管你是否新建，你的库是不是老的
不要浪费我们的时间

**Comment by tw20510946** [comment]
> 甭管你是否新建，你的库是不是老的 不要浪费我们的时间

用的是 “JimuReport v1.9.1版本带仪表盘大屏(绿色免安装版).zip”  里边自带的脚本，判断不了是不是老的。

**Comment by zhangdaiscott** [comment]
试试这个依赖
```
 <dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>jimureport-spring-boot-starter</artifactId>
            <version>1.9.5-SNAPSHOT</version>
 </dependency>
```
