### ISSUE TITLE
导出大数据报错 Network Error

### ISSUE THREAD

**Issue by catlvsuger** [jeecgboot/JimuReport#3281]
##### 错误日志&截图：：Error: Network Error
    at e.exports (axios.min.js:2:9633)
    at l.onerror (axios.min.js:2:8398)
Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR   接口： /jeecg-boot/jmreport/exportAllExcelStream

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
你可以试下最新版

**Comment by zhangdaiscott** [comment]
印象中改过大数据报错的问题

**Comment by catlvsuger** [comment]
很奇怪，没加CDN，这个数据量是正常导出的，好，我试下最新版本

**Comment by zhangdaiscott** [comment]
那就是CDN的js和本地的不一致

**Comment by catlvsuger** [comment]
处理了，CDN设置问题，超时了
