### ISSUE TITLE
升级到1.3.78版本后 没开启MongoDB 控制台 Exception opening socket

### ISSUE THREAD

**Issue by yueyunp** [jeecgboot/JimuReport#465]
##### 版本号：
1.3.78

##### 问题描述：
没开启MongoDB 控制台 Exception opening socket     
不想配置MongoDB

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/88695123/129498528-a740f0fd-53e0-4f8f-b4e4-d7a2f38ce67e.png)
2021-08-16 08:57:47.460 [cluster-ClusterId{value='6119b80a97bfc306dcfed504', description='null'}-localhost:27017] INFO  org.mongodb.driver.cluster- Exception in monitor thread while connecting to server localhost:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:67)
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:126)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:64)
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:62)
	... 3 common frames omitted

##### 重现步骤：
启动就会有错

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
试试这个版本，配置jeecg私服

```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.79</version>
</dependency>
```

**Comment by zhangdaiscott** [comment]
你运行的是什么项目？你的springboot版本？

**Comment by yueyunp** [comment]
就是正常的微服务  spring boot 版本 2.1.13.RELEASE

**Comment by yueyunp** [comment]
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.79</version>
</dependency>  
这个版本我还没试

**Comment by zhangdaiscott** [comment]
做了改造，等下个版本升级看看
