### ISSUE TITLE
minidao-pe-1.8.4.jar包中的ognl-2.6.11包不兼容ognl-3.2.6版本

### ISSUE THREAD

**Issue by Ferris2106** [jeecgboot/JimuReport#468]
##### 版本号：
1.3.78

##### 问题描述：
minidao-pe-1.8.4.jar包中的ognl-2.6.11包不兼容ognl-3.2.6版本，可否升级至3.2.6版本
解决方案参考：https://blog.csdn.net/LX928525166/article/details/82699572
##### 错误日志&截图：
08-16 10:08:38.373|ERROR|c.b.c.c.c.c.GlobalExceptionHandlerResolver:35|http-nio-18008-exec-8||全局异常信息 ex=MemberAccess implementation must be provided!
java.lang.RuntimeException: MemberAccess implementation must be provided!
	at ognl.OgnlContext.<init>(OgnlContext.java:140)
	at ognl.OgnlContext.<init>(OgnlContext.java:110)
	at ognl.Ognl.createDefaultContext(Ognl.java:159)
	at ognl.Ognl.getValue(Ognl.java:646)
	at ognl.Ognl.getValue(Ognl.java:704)
	at ognl.Ognl.getValue(Ognl.java:674)
	at org.jeecgframework.minidao.aop.MiniDaoHandler.installPlaceholderSqlParam(MiniDaoHandler.java:727)
	at org.jeecgframework.minidao.aop.MiniDaoHandler.invoke(MiniDaoHandler.java:119)
	at com.sun.proxy.$Proxy126.pageList(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
![image](https://user-images.githubusercontent.com/87572229/129502583-3ea393d3-b4d0-439f-b160-b1aab6b7a687.png)

##### 重现步骤：
springboot项目（已经引入了ognl-3.2.6版本）集成积木报表，启动项目，访问积木报表页面，报错如上。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题报表提供SQL脚本或在官网制作报表并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
依赖冲突，自己排除吧

**Comment by zhangdaiscott** [comment]
minidao-pe 可以升级到1.8.5 试试

**Comment by zhangdaiscott** [comment]
下个版本会升到3.2.21
