### ISSUE TITLE
java.lang.NumberFormatException: For input string:

### ISSUE THREAD

**Issue by Mynameislyc** [jeecgboot/JimuReport#550]
##### 版本号：
1.3.796

##### 问题描述：
操作流程：
【图型报表】->【新建报表】->【设计】->【插入图表】->【普通柱形图】

静态测试数据：
[{"value":1,"name":"陈大全"},{"value":2,"name":"李工艺"}]

![image](https://user-images.githubusercontent.com/23158982/133406664-6812d8ee-64a4-4c37-8f65-40678b3b8951.png)

![image](https://user-images.githubusercontent.com/23158982/133406096-d95ae5ac-3bd9-4414-8fbf-d5c704e45f8e.png)

保存后，在预览页面点击【导出Excel】

![image](https://user-images.githubusercontent.com/23158982/133406468-3a53a26a-c369-4530-857e-3bcb06d535c8.png)

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/23158982/133404977-80f8aa2c-19c5-4a1c-8360-0da189f9e27e.png)

java.lang.NumberFormatException: For input string: "497.994"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:1502)
	at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:469)
	at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:156)
	at org.jeecg.modules.jmreport.desreport.service.a.k.exportExcel(JmReportExportExcelImpl.java:127)
	at org.jeecg.modules.jmreport.desreport.a.a.a(DesignReportController.java:1010)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

##### 重现步骤：
导出excel表时必现；

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by 1298191366** [comment]
我集成之后没有发现该问题，你用下图所示导出来一份，后者看看jar是否下载下来
![image](https://user-images.githubusercontent.com/30997828/133430209-b8fc003e-1c53-46bb-91c3-b803dadc9df0.png)

**Comment by 1298191366** [comment]
后者你去官网试一试，如果可以了，那就是当前版本也有问题

**Comment by lvdandan16** [comment]
因长时间未回复，关闭此任务
