### ISSUE TITLE
使用Excel导出的时候出现了Blank expression的异常提示

### ISSUE THREAD

**Issue by voyager-fu** [jeecgboot/JimuReport#859]
##### 版本号：
1.4.2

##### 问题描述：
之前使用了半个多月一直没问题，也没有更改过版本号，今天再使用Excel导出的时候出现了Blank expression的异常提示

##### 错误日志&截图：
2022-03-2513:44:31.560 [http-nio-18201-exec-6] INFO c.x.d.a.a.c.security.base.BaseSecurityInterceptor - request1: /jmreport/exportAllExcelStream
2022-03-2513:44:31.565 [http-nio-18201-exec-6] INFO c.x.d.a.a.c.security.base.BaseSecurityInterceptor - firequest:/jmreport/exportAllExcelStream
2022-03-2513:44:31.583 [http-nio-18201-exec-6] INFO org.jeecg.modules.jmreport.desreport.service.a.k - 多数据源导出excel
2022-03-2513:44:31.583 [http-nio-18201-exec-6] INFO org.jeecg.modules.jmreport.desreport.service.a.k - 分页导出excel
2022-03-2513:44:31.583 [http-nio-18201-exec-6] INFO org.jeecg.modules.jmreport.desreport.service.a.k - 分页数据源的code：
2022-03-2513:44:31.583 [http-nio-18201-exec-6] INFO org.jeecg.modules.jmreport.desreport.service.a.k - 每页页数：
2022-03-2513:44:31.583 [http-nio-18201-exec-6] INFO org.jeecg.modules.jmreport.desreport.service.a.k - 数据源code长度:
2022-03-2513:44:31.583 [http-nio-18201-exec-6] INFO org.jeecg.modules.jmreport.desreport.service.a.k - 数据源集合数据::[]
2022-03-2513:44:31.611 [http-nio-18201-exec-6] INFO org.jeecg.modules.jmreport.desreport.service.a.e - ------报表
2022-03-2513:44:31.928 [http-nio-18201-exec-6] ERROR c.x.dvoice.framework.common.GlobalExceptionHandler - exception:
com.googlecode.aviator.exception.CompileExpressionErrorException: Blank expression
at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1419)
at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1413)
at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1400)
at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1535)
at org.jeecg.modules.jmreport.desreport.express.b.a(ExpressUtil.java:262)
at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:259)
at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:172)
at org.jeecg.modules.jmreport.desreport.express.a.<init>(ExpressHandler.java:78)
at org.jeecg.modules.jmreport.desreport.express.b.a(ExpressUtil.java:239)
at org.jeecg.modules.jmreport.desreport.service.a.e.show(JimuReportServiceImpl.java:3545)
at org.jeecg.modules.jmreport.desreport.service.a.e$$FastClassBySpringCGLIB$$4daca651.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
at org.jeecg.modules.jmreport.desreport.service.a.e$$EnhancerBySpringCGLIB$$959bd496.show(<generated>)
at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:258)
at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:213)
at org.jeecg.modules.jmreport.desreport.service.a.k.exportExcel(JmReportExportExcelImpl.java:117)
at org.jeecg.modules.jmreport.desreport.a.a.b(DesignReportController.java:1069)
at sun.reflect.GeneratedMethodAccessor1696.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at cn.stylefeng.roses.kernel.security.xss.XssFilter.doFilter(XssFilter.java:66)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)

![image](https://user-images.githubusercontent.com/57829162/160070929-757f9c2d-d432-43e9-8cda-234d23542d1a.png)

##### 重现步骤：
点击导出Excel，下载Excel文件之后，里面出现500的异常描述

**Comment by lvdandan16** [comment]
导出报表配置及数据

**Comment by voyager-fu** [comment]
找到问题了，因为导出的数据里面，有个单独的“=”，去掉之后，就正常了；但是仍然不清楚为啥一个单独的“=”会引起报错 @lvdandan16

**Comment by voyager-fu** [comment]
找到原因了，源码里有个地方会把“=”替换成空字符串，只有“=”的情况下，会只剩空字符串，AviatorEvaluatorInstance.compile的时候会直接报错
![QQ图片20220402110706](https://user-images.githubusercontent.com/57829162/161363531-8bf37549-a1f7-448e-80fc-00edf2020b23.png)
![QQ图片20220402110751](https://user-images.githubusercontent.com/57829162/161363540-764842f3-9c15-446b-b6b0-fff5f7c2602a.png)

**Comment by lvdandan16** [comment]
收录 ty

**Comment by 1298191366** [comment]
已修复，待新版本发布
