### ISSUE TITLE
导出的excel打不开

### ISSUE THREAD

**Issue by zDream** [jeecgboot/JimuReport#893]
##### 版本号：
1.4.32

##### 问题描述：
生产环境，导出的excel打不开，jmreport/exportAllExcelStream接口报空指针，

##### 错误日志&截图：
空指针异常 
content: 
java.lang.NullPointerException: null
	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264) ~[na:1.8.0_212] 
	at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219) ~[na:1.8.0_212]
	at sun.awt.FontConfiguration.init(FontConfiguration.java:107) ~[na:1.8.0_212]
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774) ~[na:1.8.0_212]
	at sun.font.SunFontManager$2.run(SunFontManager.java:431) ~[na:1.8.0_212]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_212]
	at sun.font.SunFontManager.<init>(SunFontManager.java:376) ~[na:1.8.0_212]
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35) ~[na:1.8.0_212]
	at sun.awt.X11FontManager.<init>(X11FontManager.java:57) ~[na:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_212]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_212]
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83) ~[na:1.8.0_212]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_212]
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74) ~[na:1.8.0_212]
	at java.awt.Font.getFont2D(Font.java:491) ~[na:1.8.0_212]
	at java.awt.Font.canDisplayUpTo(Font.java:2060) ~[na:1.8.0_212]
	at java.awt.font.TextLayout.singleFont(TextLayout.java:470) ~[na:1.8.0_212]
	at java.awt.font.TextLayout.<init>(TextLayout.java:531) ~[na:1.8.0_212]
	at org.apache.poi.ss.util.SheetUtil.getDefaultCharWidth(SheetUtil.java:273) ~[poi-4.1.0.jar!/:4.1.0]
	at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.<init>(AutoSizeColumnTracker.java:117) ~[poi-ooxml-4.1.0.jar!/:4.1.0]
	at org.apache.poi.xssf.streaming.SXSSFSheet.<init>(SXSSFSheet.java:82) ~[poi-ooxml-4.1.0.jar!/:4.1.0]
	at org.apache.poi.xssf.streaming.SXSSFSheet.<init>(SXSSFSheet.java:82) ~[poi-ooxml-4.1.0.jar!/:4.1.0]
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createAndRegisterSXSSFSheet(SXSSFWorkbook.java:674) ~[poi-ooxml-4.1.0.jar!/:4.1.0]
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:695) ~[poi-ooxml-4.1.0.jar!/:4.1.0]
	at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:546) ~[jimureport-spring-boot-starter-1.4.32.jar!/:2.0.0]
	at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:237) ~[jimureport-spring-boot-starter-1.4.32.jar!/:2.0.0]
	at org.jeecg.modules.jmreport.desreport.service.a.k.exportExcel(JmReportExportExcelImpl.java:116) ~[jimureport-spring-boot-starter-1.4.32.jar!/:2.0.0]
	at org.jeecg.modules.jmreport.desreport.a.a.b(DesignReportController.java:1087) ~[jimureport-spring-boot-starter-1.4.32.jar!/:2.0.0]
	at org.jeecg.modules.jmreport.desreport.a.a$$FastClassBySpringCGLIB$$91776b06.invoke(<generated>) ~[jimureport-spring-boot-starter-1.4.32.jar!/:2.0.0]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) [spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) [spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at com.xinzhirun.xzrcaradmin.aop.LogAspect.around(LogAspect.java:55) ~[classes!/:2.2.1.RELEASE]
	at sun.reflect.GeneratedMethodAccessor292.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) [spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) [spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) [spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) [spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) [spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) [spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) [spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) [spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.jeecg.modules.jmreport.desreport.a.a$$EnhancerBySpringCGLIB$$9257c5d1.b(<generated>) [jimureport-spring-boot-starter-1.4.32.jar!/:2.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) [spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) [spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) [spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888) [spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) [spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) [spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) [spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
![image](https://user-images.githubusercontent.com/16067566/161910677-8b637b65-5491-4ed5-bceb-3cc794df8178.png)
文件是锁定的，不知道是不是和这个有关系
![image](https://user-images.githubusercontent.com/16067566/161910752-8e93635e-c59a-4d68-b65b-ab6f61fe2e68.png)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zDream** [comment]
生产环境报空指针，本地环境没问题

**Comment by zDream** [comment]
已解决，是因为docker镜像没有字段的原因
https://blog.csdn.net/weixin_42389247/article/details/108083842?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1.pc_relevant_default&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1.pc_relevant_default&utm_relevant_index=2
