### ISSUE TITLE
1.4.2版本查看报表时报系统错误

### ISSUE THREAD

**Issue by joker-zxs** [jeecgboot/JimuReport#919]
##### 版本号：
1.4.2

##### 问题描述：

查看报表时报错

java.io.IOException: Duplicate accept detected. This is a known OS bug. Please consider reporting that you are affected: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1924298
  at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:545)
  at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:78)
  at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:129)
  at java.lang.Thread.run(Thread.java:745)

##### 错误日志&截图：
无

##### 重现步骤：
在本地集成完毕,在同事电脑上查看报表时后台会报错,但是不影响查看报表,只是耗时过长,时间大约7秒左右

**Comment by lvdandan16** [comment]
这是服务器的错误吧

**Comment by lvdandan16** [comment]
因长时间未回复，暂时关闭此问题
