### ISSUE TITLE
Method code too large!错误

### ISSUE THREAD

**Issue by szs0321** [jeecgboot/JimuReport#932]
##### 版本号：
1.3.x-1.5

##### 问题描述：
报表sql查询结果>3000条 不分页会出现 : Method code too large!错误
![Snipaste_2022-04-19_11-03-14](https://user-images.githubusercontent.com/22042231/163911917-9b9769d7-9fc0-427a-b97e-9b5f9a246f4b.jpg)

![Snipaste_2022-04-19_11-01-55](https://user-images.githubusercontent.com/22042231/163911921-87f97db8-0472-461f-a2cb-287a08dce71b.jpg)

##### 错误日志&截图：
java.lang.RuntimeException: Method code too large!

	at com.googlecode.aviator.asm.MethodWriter.getSize(MethodWriter.java:1792) ~[aviator-5.2.6.jar!/:na]

	at com.googlecode.aviator.asm.ClassWriter.toByteArray(ClassWriter.java:736) ~[aviator-5.2.6.jar!/:na]

	at com.googlecode.aviator.code.asm.ASMCodeGenerator.getResult(ASMCodeGenerator.java:831) ~[aviator-5.2.6.jar!/:na]

	at com.googlecode.aviator.code.OptimizeCodeGenerator.getResult(OptimizeCodeGenerator.java:440) ~[aviator-5.2.6.jar!/:na]

	at com.googlecode.aviator.parser.ExpressionParser.parse(ExpressionParser.java:1115) ~[aviator-5.2.6.jar!/:na]

	at com.googlecode.aviator.parser.ExpressionParser.parse(ExpressionParser.java:1120) ~[aviator-5.2.6.jar!/:na]

	at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:1494) ~[aviator-5.2.6.jar!/:na]

	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1455) ~[aviator-5.2.6.jar!/:na]

	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1413) ~[aviator-5.2.6.jar!/:na]

	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1400) ~[aviator-5.2.6.jar!/:na]

	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1535) ~[aviator-5.2.6.jar!/:na]

	at org.jeecg.modules.jmreport.desreport.express.ExpressUtil.a(ExpressUtil.java:276) ~[jimureport-spring-boot-starter-1.4.32.jar!/:2.0.0]

	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:290) ~[jimureport-spring-boot-starter-1.4.32.jar!/:2.0.0]

	at org.jeecg.modules.jmreport.desreport.express.a.a(ExpressHandler.java:203) ~[jimureport-spring-boot-starter-1.4.32.jar!/:2.0.0]

	at org.jeecg.modules.jmreport.desreport.express.a.<init>(ExpressHandler.java:78) ~[jimureport-spring-boot-starter-1.4.32.jar!/:2.0.0]

	at org.jeecg.modules.jmreport.desreport.express.ExpressUtil.a(ExpressUtil.java:253) ~[jimureport-spring-boot-starter-1.4.32.jar!/:2.0.0]

	at org.jeecg.modules.jmreport.desreport.service.a.e.show(JimuReportServiceImpl.java:3691) ~[jimureport-spring-boot-starter-1.4.32.jar!/:2.0.0]

	at org.jeecg.modules.jmreport.desreport.service.a.e$$FastClassBySpringCGLIB$$4daca651.invoke(<generated>) ~[jimureport-spring-boot-starter-1.4.32.jar!/:2.0.0]

	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.5.jar!/:5.3.5]

	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.3.5.jar!/:5.3.5]

	at org.jeecg.modules.jmreport.desreport.service.a.e$$EnhancerBySpringCGLIB$$4a824fe2.show(<generated>) ~[jimureport-spring-boot-starter-1.4.32.jar!/:2.0.0]

	at org.jeecg.modules.jmreport.desreport.a.a.a(DesignReportController.java:341) ~[jimureport-spring-boot-starter-1.4.32.jar!/:2.0.0]

	at sun.reflect.GeneratedMethodAccessor285.invoke(Unknown Source) ~[na:na]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_292]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_292]

	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) [spring-web-5.3.5.jar!/:5.3.5]

	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) [spring-web-5.3.5.jar!/:5.3.5]

	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) [spring-webmvc-5.3.5.jar!/:5.3.5]

	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) [spring-webmvc-5.3.5.jar!/:5.3.5]

	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) [spring-webmvc-5.3.5.jar!/:5.3.5]

	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.3.5.jar!/:5.3.5]

	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060) [spring-webmvc-5.3.5.jar!/:5.3.5]

	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962) [spring-webmvc-5.3.5.jar!/:5.3.5]

	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.5.jar!/:5.3.5]

	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) [spring-webmvc-5.3.5.jar!/:5.3.5]

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:497) [jakarta.servlet-api-4.0.4.jar!/:4.0.4]

	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.5.jar!/:5.3.5]

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) [jakarta.servlet-api-4.0.4.jar!/:4.0.4]

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.44.jar!/:9.0.44]

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.3.5.jar!/:5.3.5]

	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.5.jar!/:5.3.5]

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.3.5.jar!/:5.3.5]

	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.5.jar!/:5.3.5]

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) [spring-boot-actuator-2.4.4.jar!/:2.4.4]

	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.5.jar!/:5.3.5]

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.5.jar!/:5.3.5]

	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.5.jar!/:5.3.5]

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_292]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_292]

	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.44.jar!/:9.0.44]

	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_292]

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[报表设计SQL脚本](http://report.jeecg.com/2376604)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by szs0321** [comment]
版本填写错误
