### ISSUE TITLE
导出excel时出现json反序列化报错

### ISSUE THREAD

**Issue by voyager-fu** [jeecgboot/JimuReport#953]
##### 版本号：
1.4.2

##### 问题描述：
业务数据包含字符【 " 】（英文双引号），json反序列化报错

##### 错误日志&截图：
com.alibaba.fastjson.JSONException: syntax error, position at 41, name text
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:645)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:581)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:581)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:581)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1430)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1390)
	at com.alibaba.fastjson.JSON.parse(JSON.java:181)
	at com.alibaba.fastjson.JSON.parse(JSON.java:191)
	at com.alibaba.fastjson.JSON.parse(JSON.java:244)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:248)
	at org.jeecg.modules.jmreport.desreport.render.a.d.render(TableRenderStrategy.java:121)
	at org.jeecg.modules.jmreport.desreport.render.a.a.b.a(BaseBaseRenderStrategy.java:349)
	at org.jeecg.modules.jmreport.desreport.render.a.a.b.b(BaseBaseRenderStrategy.java:258)
	at org.jeecg.modules.jmreport.desreport.render.a.a.b.render(BaseBaseRenderStrategy.java:57)
	at org.jeecg.modules.jmreport.desreport.service.a.e.a(JimuReportServiceImpl.java:3644)
	at org.jeecg.modules.jmreport.desreport.service.a.e.show(JimuReportServiceImpl.java:3543)
	at org.jeecg.modules.jmreport.desreport.service.a.e$$FastClassBySpringCGLIB$$4daca651.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at org.jeecg.modules.jmreport.desreport.service.a.e$$EnhancerBySpringCGLIB$$5c911a24.show(<generated>)
	at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:258)
	at org.jeecg.modules.jmreport.desreport.service.a.k.a(JmReportExportExcelImpl.java:213)
	at org.jeecg.modules.jmreport.desreport.service.a.k.exportExcel(JmReportExportExcelImpl.java:117)
	at org.jeecg.modules.jmreport.desreport.a.a.b(DesignReportController.java:1069)

**Comment by suweiquan888** [comment]
这个导出报错，是升级了json的jar包吗，能明确的说明下吗
